import { NextResponse } from "next/server";
import { db } from "@/db";
import { transactions, assets, liabilities } from "@/db/schema";
import { eq, and, gte, lte, desc } from "drizzle-orm";

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");
    const type = searchParams.get("type");
    const assetId = searchParams.get("assetId");
    const liabilityId = searchParams.get("liabilityId");
    const startDate = searchParams.get("startDate");
    const endDate = searchParams.get("endDate");
    const categoryId = searchParams.get("categoryId");
    const limit = searchParams.get("limit");

    if (id) {
      const tx = await db
        .select()
        .from(transactions)
        .where(eq(transactions.id, Number(id)));
      if (!tx.length) {
        return NextResponse.json({ error: "账目不存在" }, { status: 404 });
      }
      return NextResponse.json(tx[0]);
    }

    const conditions = [];
    if (type) conditions.push(eq(transactions.type, type as "asset_value_change" | "asset_income" | "liability_repayment" | "liability_principal_change" | "expense" | "income" | "transfer" | "reconciliation"));
    if (assetId) conditions.push(eq(transactions.assetId, Number(assetId)));
    if (liabilityId) conditions.push(eq(transactions.liabilityId, Number(liabilityId)));
    if (categoryId) conditions.push(eq(transactions.categoryId, Number(categoryId)));
    if (startDate) conditions.push(gte(transactions.transactionDate, new Date(startDate)));
    if (endDate) conditions.push(lte(transactions.transactionDate, new Date(endDate)));

    let query = db
      .select()
      .from(transactions)
      .orderBy(desc(transactions.transactionDate));

    const result = conditions.length
      ? await query.where(and(...conditions)).limit(limit ? Number(limit) : 500)
      : await query.limit(limit ? Number(limit) : 500);

    return NextResponse.json(result);
  } catch {
    return NextResponse.json(
      { error: "获取账目列表失败" },
      { status: 500 }
    );
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const result = await db
      .insert(transactions)
      .values({
        type: body.type,
        categoryId: body.categoryId ?? null,
        assetId: body.assetId ?? null,
        liabilityId: body.liabilityId ?? null,
        amount: body.amount,
        principalPart: body.principalPart ?? 0,
        interestPart: body.interestPart ?? 0,
        description: body.description,
        transactionDate: new Date(body.transactionDate),
        isAutoGenerated: body.isAutoGenerated ?? false,
        reconciliationId: body.reconciliationId ?? null,
        note: body.note ?? null,
      })
      .returning();

    // 根据账目类型自动更新关联的资产或负债
    const tx = result[0];

    if (tx.type === "asset_value_change" && tx.assetId) {
      await db
        .update(assets)
        .set({ currentValue: body.newAssetValue ?? body.amount, updatedAt: new Date() })
        .where(eq(assets.id, tx.assetId));
    }

    if (tx.type === "liability_repayment" && tx.liabilityId) {
      const currentLiability = await db
        .select()
        .from(liabilities)
        .where(eq(liabilities.id, tx.liabilityId));
      if (currentLiability.length) {
        const newRemaining = currentLiability[0].remainingPrincipal - (tx.principalPart ?? 0);
        await db
          .update(liabilities)
          .set({
            remainingPrincipal: Math.max(0, newRemaining),
            updatedAt: new Date(),
          })
          .where(eq(liabilities.id, tx.liabilityId));
      }
    }

    if (tx.type === "liability_principal_change" && tx.liabilityId) {
      const currentLiability = await db
        .select()
        .from(liabilities)
        .where(eq(liabilities.id, tx.liabilityId));
      if (currentLiability.length) {
        const newRemaining = currentLiability[0].remainingPrincipal + tx.amount;
        await db
          .update(liabilities)
          .set({
            remainingPrincipal: newRemaining,
            updatedAt: new Date(),
          })
          .where(eq(liabilities.id, tx.liabilityId));
      }
    }

    return NextResponse.json(tx, { status: 201 });
  } catch {
    return NextResponse.json(
      { error: "创建账目失败" },
      { status: 500 }
    );
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json();
    const { id, ...updates } = body;
    if (updates.transactionDate) {
      updates.transactionDate = new Date(updates.transactionDate);
    }
    const result = await db
      .update(transactions)
      .set(updates)
      .where(eq(transactions.id, id))
      .returning();

    if (!result.length) {
      return NextResponse.json({ error: "账目不存在" }, { status: 404 });
    }
    return NextResponse.json(result[0]);
  } catch {
    return NextResponse.json(
      { error: "更新账目失败" },
      { status: 500 }
    );
  }
}

export async function DELETE(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const id = Number(searchParams.get("id"));
    await db.delete(transactions).where(eq(transactions.id, id));
    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json(
      { error: "删除账目失败" },
      { status: 500 }
    );
  }
}
