import { NextResponse } from "next/server";
import { db } from "@/db";
import { transactions, assets, liabilities } from "@/db/schema";
import { eq, and, gte, lte, desc } from "drizzle-orm";
import { requireUser } from "@/lib/auth";

export async function GET(request: Request) {
  try {
    const user = await requireUser();
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");
    const type = searchParams.get("type");
    const assetId = searchParams.get("assetId");
    const liabilityId = searchParams.get("liabilityId");
    const startDate = searchParams.get("startDate");
    const endDate = searchParams.get("endDate");
    const categoryId = searchParams.get("categoryId");
    const limit = searchParams.get("limit");

    if (id) {
      const tx = await db
        .select()
        .from(transactions)
        .where(and(eq(transactions.id, Number(id)), eq(transactions.userId, user.id)));
      if (!tx.length) {
        return NextResponse.json({ error: "账目不存在" }, { status: 404 });
      }
      return NextResponse.json(tx[0]);
    }

    const conditions = [eq(transactions.userId, user.id)];
    if (type) conditions.push(eq(transactions.type, type as "asset_value_change" | "asset_income" | "liability_repayment" | "liability_principal_change" | "expense" | "income" | "transfer" | "reconciliation"));
    if (assetId) conditions.push(eq(transactions.assetId, Number(assetId)));
    if (liabilityId) conditions.push(eq(transactions.liabilityId, Number(liabilityId)));
    if (categoryId) conditions.push(eq(transactions.categoryId, Number(categoryId)));
    if (startDate) conditions.push(gte(transactions.transactionDate, new Date(startDate)));
    if (endDate) conditions.push(lte(transactions.transactionDate, new Date(endDate)));

    const result = await db
      .select()
      .from(transactions)
      .where(and(...conditions))
      .orderBy(desc(transactions.transactionDate))
      .limit(limit ? Number(limit) : 500);

    return NextResponse.json(result);
  } catch (e) {
    if ((e as Error).message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "请先登录" }, { status: 401 });
    }
    return NextResponse.json(
      { error: "获取账目列表失败" },
      { status: 500 }
    );
  }
}

export async function POST(request: Request) {
  try {
    const user = await requireUser();
    const body = await request.json();
    const result = await db.insert(transactions).values({
      userId: user.id,
      type: body.type,
      categoryId: body.categoryId ?? null,
      assetId: body.assetId ?? null,
      liabilityId: body.liabilityId ?? null,
      amount: body.amount,
      principalPart: body.principalPart ?? 0,
      interestPart: body.interestPart ?? 0,
      description: body.description,
      transactionDate: new Date(body.transactionDate),
      isAutoGenerated: body.isAutoGenerated ?? false,
      reconciliationId: body.reconciliationId ?? null,
      note: body.note ?? null,
    });

    const insertId = Number(result[0].insertId);
    const [tx] = await db
      .select()
      .from(transactions)
      .where(eq(transactions.id, insertId));

    if (tx.type === "asset_value_change" && tx.assetId) {
      await db
        .update(assets)
        .set({ currentValue: body.newAssetValue ?? body.amount, updatedAt: new Date() })
        .where(and(eq(assets.id, tx.assetId), eq(assets.userId, user.id)));
    }

    if (tx.type === "liability_repayment" && tx.liabilityId) {
      const currentLiability = await db
        .select()
        .from(liabilities)
        .where(and(eq(liabilities.id, tx.liabilityId), eq(liabilities.userId, user.id)));
      if (currentLiability.length) {
        const newRemaining = currentLiability[0].remainingPrincipal - (tx.principalPart ?? 0);
        await db
          .update(liabilities)
          .set({
            remainingPrincipal: Math.max(0, newRemaining),
            updatedAt: new Date(),
          })
          .where(and(eq(liabilities.id, tx.liabilityId), eq(liabilities.userId, user.id)));
      }
    }

    if (tx.type === "liability_principal_change" && tx.liabilityId) {
      const currentLiability = await db
        .select()
        .from(liabilities)
        .where(and(eq(liabilities.id, tx.liabilityId), eq(liabilities.userId, user.id)));
      if (currentLiability.length) {
        const newRemaining = currentLiability[0].remainingPrincipal + tx.amount;
        await db
          .update(liabilities)
          .set({
            remainingPrincipal: newRemaining,
            updatedAt: new Date(),
          })
          .where(and(eq(liabilities.id, tx.liabilityId), eq(liabilities.userId, user.id)));
      }
    }

    return NextResponse.json(tx, { status: 201 });
  } catch (e) {
    if ((e as Error).message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "请先登录" }, { status: 401 });
    }
    return NextResponse.json(
      { error: "创建账目失败" },
      { status: 500 }
    );
  }
}

export async function PUT(request: Request) {
  try {
    const user = await requireUser();
    const body = await request.json();
    const { id, ...updates } = body;
    if (updates.transactionDate) {
      updates.transactionDate = new Date(updates.transactionDate);
    }
    await db
      .update(transactions)
      .set(updates)
      .where(and(eq(transactions.id, id), eq(transactions.userId, user.id)));

    const [updated] = await db
      .select()
      .from(transactions)
      .where(eq(transactions.id, id));

    if (!updated) {
      return NextResponse.json({ error: "账目不存在" }, { status: 404 });
    }
    return NextResponse.json(updated);
  } catch (e) {
    if ((e as Error).message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "请先登录" }, { status: 401 });
    }
    return NextResponse.json(
      { error: "更新账目失败" },
      { status: 500 }
    );
  }
}

export async function DELETE(request: Request) {
  try {
    const user = await requireUser();
    const { searchParams } = new URL(request.url);
    const id = Number(searchParams.get("id"));
    await db
      .delete(transactions)
      .where(and(eq(transactions.id, id), eq(transactions.userId, user.id)));
    return NextResponse.json({ success: true });
  } catch (e) {
    if ((e as Error).message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "请先登录" }, { status: 401 });
    }
    return NextResponse.json(
      { error: "删除账目失败" },
      { status: 500 }
    );
  }
}
