"use client";

import { useState, useEffect } from "react";
import { AssetForm } from "@/components/Forms";
import { BalanceChart } from "@/components/BalanceChart";
import { formatMoney, formatDate, getAssetTypeLabel } from "@/lib/utils";

interface Asset {
  id: number;
  name: string;
  type: string;
  currentValue: number;
  monthlyIncome: number;
  annualYield: number;
  isActive: boolean;
  note: string | null;
}

interface Transaction {
  id: number;
  type: string;
  amount: number;
  description: string;
  transactionDate: string;
  isAutoGenerated: boolean;
}

export default function AssetsPage() {
  const [assets, setAssets] = useState<Asset[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [details, setDetails] = useState<Record<number, Transaction[]>>({});

  useEffect(() => {
    let mounted = true;
    fetch("/api/assets")
      .then((r) => r.json())
      .then((data) => {
        if (mounted) {
          setAssets(data);
          setLoading(false);
          if (data.length > 0 && !selectedId) setSelectedId(data[0].id);
        }
      });
    return () => {
      mounted = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const fetchAssets = () => {
    fetch("/api/assets")
      .then((r) => r.json())
      .then((data) => {
        setAssets(data);
        if (selectedId && !data.find((a: Asset) => a.id === selectedId)) {
          setSelectedId(data.length > 0 ? data[0].id : null);
        }
      });
  };

  const handleDelete = async (id: number) => {
    if (!confirm("确定要删除这项资产吗？")) return;
    await fetch(`/api/assets?id=${id}`, { method: "DELETE" });
    if (selectedId === id) setSelectedId(null);
    fetchAssets();
  };

  const loadDetails = async (assetId: number) => {
    if (details[assetId]) return;
    const res = await fetch(`/api/transactions?assetId=${assetId}&limit=50`);
    const data = await res.json();
    setDetails((d) => ({ ...d, [assetId]: data }));
  };

  const handleSelect = (id: number) => {
    setSelectedId(id);
    loadDetails(id);
  };

  const txTypeLabel = (type: string) => {
    const map: Record<string, string> = {
      income: "收入",
      expense: "支出",
      asset_value_change: "价值变动",
      asset_income: "资产收益",
    };
    return map[type] ?? type;
  };

  const selected = assets.find((a) => a.id === selectedId);
  const selectedTxs = selectedId ? details[selectedId] ?? null : null;

  // Compute running balances for transaction table (oldest-first)
  const txsWithBalance = (() => {
    if (!selected || !selectedTxs || selectedTxs.length === 0) return [];
    const sorted = [...selectedTxs].reverse(); // oldest first
    // Walk backwards from current to get initial balance
    let balance = selected.currentValue;
    for (let i = sorted.length - 1; i >= 0; i--) {
      const t = sorted[i];
      if (t.type === "income" || t.type === "asset_income") {
        balance -= t.amount;
      } else if (t.type === "expense") {
        balance += t.amount;
      }
    }
    // Walk forward computing balance after each transaction
    const result: (Transaction & { balance: number })[] = [];
    for (const t of sorted) {
      if (t.type === "income" || t.type === "asset_income") {
        balance += t.amount;
      } else if (t.type === "expense") {
        balance -= t.amount;
      }
      result.push({ ...t, balance });
    }
    return result.reverse(); // newest first for display
  })();

  // Monthly chart data: group transactions by month, show ending balance per month
  const chartData = (() => {
    if (!selected || !selectedTxs || selectedTxs.length === 0) return [];
    const sorted = [...selectedTxs].reverse(); // oldest first
    // Compute initial balance
    let balance = selected.currentValue;
    for (let i = sorted.length - 1; i >= 0; i--) {
      const t = sorted[i];
      if (t.type === "income" || t.type === "asset_income") {
        balance -= t.amount;
      } else if (t.type === "expense") {
        balance += t.amount;
      }
    }
    // Walk forward, track ending balance per month
    const monthMap = new Map<string, number>();
    // Add initial month
    if (sorted.length > 0) {
      const d = new Date(sorted[0].transactionDate);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
      monthMap.set(key, balance);
    }
    for (const t of sorted) {
      if (t.type === "income" || t.type === "asset_income") {
        balance += t.amount;
      } else if (t.type === "expense") {
        balance -= t.amount;
      }
      const d = new Date(t.transactionDate);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
      monthMap.set(key, balance);
    }
    const points = Array.from(monthMap.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([month, value]) => {
        const [y, m] = month.split("-");
        return { label: `${y.slice(2)}/${m}`, value };
      });
    return points.slice(-12);
  })();

  const totalValue = assets.reduce((s, a) => s + a.currentValue, 0);
  const totalIncome = assets.reduce((s, a) => s + (a.monthlyIncome ?? 0), 0);

  return (
    <div className="flex flex-col h-[calc(100vh-1rem)]">
      {/* Header */}
      <div className="flex justify-between items-center px-6 pt-4 pb-3 shrink-0">
        <h2 className="text-2xl font-bold text-white">资产管理</h2>
        <button
          onClick={() => setShowForm(!showForm)}
          className="bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          {showForm ? "收起" : "+ 添加资产"}
        </button>
      </div>

      {showForm && (
        <div className="mx-6 mb-3 bg-neutral-900 border border-neutral-800 rounded-xl p-5 shrink-0">
          <AssetForm
            onSuccess={() => {
              fetchAssets();
              setShowForm(false);
            }}
          />
        </div>
      )}

      {/* Main content: left list + right detail */}
      <div className="flex flex-1 gap-4 px-6 pb-4 min-h-0">
        {/* Left: list */}
        <div className="w-72 shrink-0 flex flex-col">
          {/* Summary */}
          <div className="grid grid-cols-2 gap-3 mb-3 shrink-0">
            <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-3">
              <p className="text-xs text-neutral-400">资产总值</p>
              <p className="text-base font-bold text-green-400 mt-0.5">
                {formatMoney(totalValue)}
              </p>
            </div>
            <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-3">
              <p className="text-xs text-neutral-400">月收入</p>
              <p className="text-base font-bold text-blue-400 mt-0.5">
                {formatMoney(totalIncome)}
              </p>
            </div>
          </div>

          {/* List */}
          <div className="flex-1 overflow-y-auto space-y-1 bg-neutral-900 border border-neutral-800 rounded-xl p-2">
            {loading ? (
              <p className="text-center text-neutral-500 py-8 text-sm">
                加载中...
              </p>
            ) : assets.length === 0 ? (
              <p className="text-center text-neutral-500 py-8 text-sm">
                暂无资产
              </p>
            ) : (
              assets.map((a) => (
                <button
                  key={a.id}
                  onClick={() => handleSelect(a.id)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${
                    selectedId === a.id
                      ? "bg-blue-600/20 border border-blue-600/40"
                      : "hover:bg-neutral-800 border border-transparent"
                  }`}
                >
                  <div className="flex justify-between items-center">
                    <p className="text-sm font-medium text-white truncate">
                      {a.name}
                    </p>
                    <p className="text-sm font-bold text-green-400 ml-2 whitespace-nowrap">
                      {formatMoney(a.currentValue)}
                    </p>
                  </div>
                  <p className="text-xs text-neutral-500 mt-0.5">
                    {getAssetTypeLabel(a.type)}
                    {(a.monthlyIncome ?? 0) > 0 && (
                      <span className="ml-1.5">
                        月入{formatMoney(a.monthlyIncome!)}
                      </span>
                    )}
                  </p>
                </button>
              ))
            )}
          </div>
        </div>

        {/* Right: detail */}
        <div className="flex-1 min-w-0 overflow-y-auto">
          {!selected ? (
            <div className="flex items-center justify-center h-full">
              <p className="text-neutral-500 text-sm">
                从左侧选择一项资产查看详情
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {/* Info cards */}
              <div className="grid grid-cols-4 gap-3">
                <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
                  <p className="text-xs text-neutral-400">当前价值</p>
                  <p className="text-lg font-bold text-green-400 mt-1">
                    {formatMoney(selected.currentValue)}
                  </p>
                </div>
                <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
                  <p className="text-xs text-neutral-400">类型</p>
                  <p className="text-lg font-bold text-white mt-1">
                    {getAssetTypeLabel(selected.type)}
                  </p>
                </div>
                <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
                  <p className="text-xs text-neutral-400">月收入</p>
                  <p className="text-lg font-bold text-blue-400 mt-1">
                    {formatMoney(selected.monthlyIncome ?? 0)}
                  </p>
                </div>
                <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
                  <p className="text-xs text-neutral-400">年化收益率</p>
                  <p className="text-lg font-bold text-white mt-1">
                    {(selected.annualYield ?? 0).toFixed(2)}%
                  </p>
                </div>
              </div>

              {/* Chart */}
              {chartData.length > 0 && (
                <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
                  <h3 className="text-sm font-medium text-white mb-3">
                    余额变动趋势
                  </h3>
                  <BalanceChart data={chartData} color="green" />
                </div>
              )}

              {/* Transactions */}
              <div className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden">
                <div className="px-4 py-3 border-b border-neutral-800">
                  <h3 className="text-sm font-medium text-white">交易明细</h3>
                </div>
                {txsWithBalance.length === 0 ? (
                    <p className="text-center text-neutral-500 py-8 text-sm">
                      暂无交易记录
                    </p>
                  ) : (
                    <table className="w-full">
                      <thead>
                        <tr className="border-b border-neutral-800">
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            日期
                          </th>
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            类型
                          </th>
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            描述
                          </th>
                          <th className="text-right text-xs text-neutral-400 px-4 py-2">
                            金额
                          </th>
                          <th className="text-right text-xs text-neutral-400 px-4 py-2">
                            余额
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {txsWithBalance.map((t) => (
                          <tr
                            key={t.id}
                            className="border-b border-neutral-800/50"
                          >
                            <td className="px-4 py-2 text-xs text-neutral-400">
                              {formatDate(t.transactionDate)}
                              {t.isAutoGenerated && (
                                <span className="ml-1 text-neutral-600">
                                  自动
                                </span>
                              )}
                            </td>
                            <td className="px-4 py-2 text-xs text-neutral-400">
                              {txTypeLabel(t.type)}
                            </td>
                            <td className="px-4 py-2 text-xs text-white">
                              {t.description}
                            </td>
                            <td
                              className={`px-4 py-2 text-xs text-right font-medium ${
                                ["income", "asset_income"].includes(t.type)
                                  ? "text-green-400"
                                  : "text-red-400"
                              }`}
                            >
                              {["income", "asset_income"].includes(t.type)
                                ? "+"
                                : "-"}
                              {formatMoney(Math.abs(t.amount))}
                            </td>
                            <td className="px-4 py-2 text-xs text-right text-white font-medium">
                              {formatMoney(t.balance)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )
                }
              </div>

              {/* Delete button */}
              <div className="flex justify-end">
                <button
                  onClick={() => handleDelete(selected.id)}
                  className="text-red-400 hover:text-red-300 text-xs border border-red-900/50 hover:border-red-800 rounded-lg px-3 py-1.5 transition-colors"
                >
                  删除此资产
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
