"use client";

import { useState, useEffect } from "react";
import { AssetForm } from "@/components/Forms";
import { formatMoney, formatDate, getAssetTypeLabel } from "@/lib/utils";

interface Asset {
  id: number;
  name: string;
  type: string;
  currentValue: number;
  monthlyIncome: number;
  annualYield: number;
  isActive: boolean;
  note: string | null;
}

interface Transaction {
  id: number;
  type: string;
  amount: number;
  description: string;
  transactionDate: string;
  isAutoGenerated: boolean;
}

export default function AssetsPage() {
  const [assets, setAssets] = useState<Asset[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [details, setDetails] = useState<Record<number, Transaction[]>>({});

  useEffect(() => {
    let mounted = true;
    fetch("/api/assets")
      .then((r) => r.json())
      .then((data) => {
        if (mounted) {
          setAssets(data);
          setLoading(false);
        }
      });
    return () => {
      mounted = false;
    };
  }, []);

  const fetchAssets = () => {
    fetch("/api/assets")
      .then((r) => r.json())
      .then((data) => setAssets(data));
  };

  const handleDelete = async (id: number) => {
    if (!confirm("确定要删除这项资产吗？")) return;
    await fetch(`/api/assets?id=${id}`, { method: "DELETE" });
    fetchAssets();
  };

  const toggleDetails = async (assetId: number) => {
    if (expandedId === assetId) {
      setExpandedId(null);
      return;
    }
    setExpandedId(assetId);
    if (!details[assetId]) {
      const res = await fetch(`/api/transactions?assetId=${assetId}&limit=20`);
      const data = await res.json();
      setDetails((d) => ({ ...d, [assetId]: data }));
    }
  };

  const txTypeLabel = (type: string) => {
    const map: Record<string, string> = {
      income: "收入",
      expense: "支出",
      asset_value_change: "价值变动",
      asset_income: "资产收益",
    };
    return map[type] ?? type;
  };

  const totalValue = assets.reduce((s, a) => s + a.currentValue, 0);
  const totalIncome = assets.reduce((s, a) => s + (a.monthlyIncome ?? 0), 0);

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-white">资产管理</h2>
          <p className="text-sm text-neutral-400 mt-1">
            管理所有资产，追踪价值和现金流
          </p>
        </div>
        <button
          onClick={() => setShowForm(!showForm)}
          className="bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          {showForm ? "收起" : "+ 添加资产"}
        </button>
      </div>

      {showForm && (
        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5">
          <AssetForm
            onSuccess={() => {
              fetchAssets();
              setShowForm(false);
            }}
          />
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
          <p className="text-sm text-neutral-400">资产总值</p>
          <p className="text-xl font-bold text-green-400 mt-1">
            {formatMoney(totalValue)}
          </p>
        </div>
        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
          <p className="text-sm text-neutral-400">月总收入</p>
          <p className="text-xl font-bold text-blue-400 mt-1">
            {formatMoney(totalIncome)}
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {loading ? (
          <div className="text-center text-neutral-500 py-8 text-sm">
            加载中...
          </div>
        ) : assets.length === 0 ? (
          <div className="text-center text-neutral-500 py-8 text-sm">
            暂无资产记录，点击上方按钮添加
          </div>
        ) : (
          assets.map((a) => (
            <div
              key={a.id}
              className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden"
            >
              <div
                className="flex items-center justify-between px-5 py-4 cursor-pointer hover:bg-neutral-800/30"
                onClick={() => toggleDetails(a.id)}
              >
                <div className="flex items-center gap-4">
                  <div>
                    <p className="text-sm font-medium text-white">{a.name}</p>
                    <p className="text-xs text-neutral-500 mt-0.5">
                      {getAssetTypeLabel(a.type)}
                      {(a.monthlyIncome ?? 0) > 0 && (
                        <span className="ml-2">月入 {formatMoney(a.monthlyIncome!)}</span>
                      )}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <p className="text-sm font-bold text-green-400">
                    {formatMoney(a.currentValue)}
                  </p>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDelete(a.id);
                    }}
                    className="text-red-400 hover:text-red-300 text-xs"
                  >
                    删除
                  </button>
                  <span
                    className={`text-neutral-500 text-xs transition-transform ${
                      expandedId === a.id ? "rotate-180" : ""
                    }`}
                  >
                    ▼
                  </span>
                </div>
              </div>

              {expandedId === a.id && (
                <div className="border-t border-neutral-800 px-5 py-3">
                  {details[a.id] ? (
                    details[a.id].length === 0 ? (
                      <p className="text-xs text-neutral-500 py-2">暂无交易记录</p>
                    ) : (
                      <table className="w-full">
                        <thead>
                          <tr>
                            <th className="text-left text-xs text-neutral-500 pb-2">日期</th>
                            <th className="text-left text-xs text-neutral-500 pb-2">类型</th>
                            <th className="text-left text-xs text-neutral-500 pb-2">描述</th>
                            <th className="text-right text-xs text-neutral-500 pb-2">金额</th>
                          </tr>
                        </thead>
                        <tbody>
                          {details[a.id].map((t) => (
                            <tr key={t.id} className="border-t border-neutral-800/50">
                              <td className="py-2 text-xs text-neutral-400">
                                {formatDate(t.transactionDate)}
                                {t.isAutoGenerated && (
                                  <span className="ml-1 text-neutral-600">自动</span>
                                )}
                              </td>
                              <td className="py-2 text-xs text-neutral-400">
                                {txTypeLabel(t.type)}
                              </td>
                              <td className="py-2 text-xs text-white">{t.description}</td>
                              <td
                                className={`py-2 text-xs text-right font-medium ${
                                  ["income", "asset_income"].includes(t.type)
                                    ? "text-green-400"
                                    : "text-red-400"
                                }`}
                              >
                                {["income", "asset_income"].includes(t.type) ? "+" : "-"}
                                {formatMoney(Math.abs(t.amount))}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    )
                  ) : (
                    <p className="text-xs text-neutral-500 py-2">加载中...</p>
                  )}
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}
