"use client";

import { useState, useEffect, type ReactNode } from "react";
import { AssetForm, TransactionForm } from "@/components/Forms";
import { BalanceChart } from "@/components/BalanceChart";
import { Modal } from "@/components/Modal";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { TransactionEditModal } from "@/components/TransactionEditModal";
import { Pagination } from "@/components/Pagination";
import {
  formatMoney,
  formatDate,
  getAssetTypeLabel,
  getIncomeFrequencyLabel,
} from "@/lib/utils";
import { runningAssetBalances } from "@/lib/ledger";

interface Asset {
  id: number;
  name: string;
  type: string;
  currentValue: number;
  monthlyIncome: number;
  annualYield: number;
  incomeFrequency: string | null;
  incomeDay: number | null;
  isActive: boolean;
  note: string | null;
}

interface Transaction {
  id: number;
  type: string;
  amount: number;
  principalPart: number;
  interestPart: number;
  description: string;
  transactionDate: string;
  isAutoGenerated: boolean;
  note: string | null;
}

const inputClass =
  "w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500";
const labelClass = "block text-sm text-neutral-400 mb-1";

function Field({
  label,
  value,
  className,
}: {
  label: string;
  value: ReactNode;
  className?: string;
}) {
  return (
    <div className="min-w-0">
      <p className="text-xs text-neutral-500">{label}</p>
      <p className={`text-sm font-medium mt-1 break-words ${className ?? "text-white"}`}>
        {value}
      </p>
    </div>
  );
}

export default function AssetsPage() {
  const [assets, setAssets] = useState<Asset[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [details, setDetails] = useState<Record<number, Transaction[]>>({});
  const [txPages, setTxPages] = useState<Record<number, number>>({});
  const txLimit = 20;
  const [selectedTxId, setSelectedTxId] = useState<number | null>(null);

  // 账户基本信息编辑
  const [editing, setEditing] = useState(false);
  const [editError, setEditError] = useState("");
  const [editLoading, setEditLoading] = useState(false);
  const [editForm, setEditForm] = useState({
    name: "",
    type: "deposit",
    currentValue: "",
    monthlyIncome: "",
    annualYield: "",
    incomeFrequency: "monthly",
    incomeDay: "",
    note: "",
  });

  // 弹窗状态
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deleteLoading, setDeleteLoading] = useState(false);
  const [showTxForm, setShowTxForm] = useState(false);
  const [editingTx, setEditingTx] = useState<Transaction | null>(null);
  const [confirmDeleteTx, setConfirmDeleteTx] = useState(false);
  const [deleteTxLoading, setDeleteTxLoading] = useState(false);

  const loadDetails = async (assetId: number) => {
    const res = await fetch(`/api/transactions?assetId=${assetId}&all=1`);
    const result = await res.json();
    setDetails((d) => ({ ...d, [assetId]: result.data ?? [] }));
    setTxPages((p) => ({ ...p, [assetId]: 1 }));
  };

  // 重新拉取账户列表，并同步刷新当前选中账户的明细
  const fetchAssets = async (preferId?: number | null) => {
    const res = await fetch("/api/assets");
    const data = await res.json();
    const list: Asset[] = Array.isArray(data) ? data : [];
    setAssets(list);
    setLoading(false);
    const wanted = preferId ?? selectedId;
    const nextId =
      wanted && list.some((a) => a.id === wanted)
        ? wanted
        : list[0]?.id ?? null;
    setSelectedId(nextId);
    if (nextId) await loadDetails(nextId);
  };

  useEffect(() => {
    let mounted = true;
    fetch("/api/assets")
      .then((r) => r.json())
      .then((data) => {
        if (!mounted) return;
        const list: Asset[] = Array.isArray(data) ? data : [];
        setAssets(list);
        setLoading(false);
        if (list.length > 0) {
          setSelectedId(list[0].id);
          loadDetails(list[0].id);
        }
      });
    return () => {
      mounted = false;
    };
  }, []);

  const handleSelect = (id: number) => {
    setSelectedId(id);
    setSelectedTxId(null);
    loadDetails(id);
  };

  const startEdit = () => {
    if (!selected) return;
    setEditError("");
    setEditForm({
      name: selected.name,
      type: selected.type,
      currentValue: String(selected.currentValue),
      monthlyIncome: String(selected.monthlyIncome ?? 0),
      annualYield: String(selected.annualYield ?? 0),
      incomeFrequency: selected.incomeFrequency ?? "monthly",
      incomeDay: selected.incomeDay != null ? String(selected.incomeDay) : "",
      note: selected.note ?? "",
    });
    setEditing(true);
  };

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selected) return;
    setEditLoading(true);
    setEditError("");
    try {
      const res = await fetch("/api/assets", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: selected.id,
          name: editForm.name,
          type: editForm.type,
          currentValue: Number(editForm.currentValue),
          monthlyIncome: Number(editForm.monthlyIncome),
          annualYield: Number(editForm.annualYield),
          incomeFrequency: editForm.incomeFrequency,
          incomeDay: editForm.incomeDay ? Number(editForm.incomeDay) : null,
          note: editForm.note || null,
        }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        setEditError(data.error || "保存失败");
        return;
      }
      setEditing(false);
      await fetchAssets(selected.id);
    } finally {
      setEditLoading(false);
    }
  };

  const handleDeleteAccount = async () => {
    if (!selected) return;
    setDeleteLoading(true);
    try {
      await fetch(`/api/assets?id=${selected.id}`, { method: "DELETE" });
      setConfirmDelete(false);
      setSelectedTxId(null);
      await fetchAssets(null);
    } finally {
      setDeleteLoading(false);
    }
  };

  const handleDeleteTx = async () => {
    if (!selectedTx) return;
    setDeleteTxLoading(true);
    try {
      await fetch(`/api/transactions?id=${selectedTx.id}`, {
        method: "DELETE",
      });
      setConfirmDeleteTx(false);
      setSelectedTxId(null);
      await fetchAssets(selectedId);
    } finally {
      setDeleteTxLoading(false);
    }
  };

  const totalPages = (id: number) =>
    Math.max(1, Math.ceil((details[id]?.length ?? 0) / txLimit));
  const currentPage = (id: number) => txPages[id] ?? 1;

  const txTypeLabel = (type: string) => {
    const map: Record<string, string> = {
      income: "收入",
      expense: "支出",
      asset_value_change: "价值变动",
      asset_income: "资产收益",
    };
    return map[type] ?? type;
  };

  const selected = assets.find((a) => a.id === selectedId);
  const selectedTxs = selectedId ? details[selectedId] ?? null : null;

  // 以流水为准：按时间从旧到新重放完整流水，得到每一笔之后的余额与这笔造成的变动
  const txsWithBalance = (() => {
    if (!selectedTxs || selectedTxs.length === 0) return [];
    const oldestFirst = [...selectedTxs].reverse(); // oldest first
    const balances = runningAssetBalances(oldestFirst);
    const rows = new Map<number, { balance: number; delta: number }>();
    oldestFirst.forEach((t, i) => {
      const prev = i === 0 ? 0 : balances[i - 1];
      rows.set(t.id, { balance: balances[i], delta: balances[i] - prev });
    });
    return selectedTxs.map((t) => ({
      ...t,
      balance: rows.get(t.id)?.balance ?? 0,
      delta: rows.get(t.id)?.delta ?? 0,
    }));
  })();

  const currentPageNum = selectedId ? currentPage(selectedId) : 1;
  const visibleTxs = txsWithBalance.slice(
    (currentPageNum - 1) * txLimit,
    currentPageNum * txLimit,
  );
  const selectedTx =
    txsWithBalance.find((t) => t.id === selectedTxId) ?? null;

  // Monthly chart data: group transactions by month, show ending balance per month
  const chartData = (() => {
    if (!selectedTxs || selectedTxs.length === 0) return [];
    const oldestFirst = [...selectedTxs].reverse(); // oldest first
    const balances = runningAssetBalances(oldestFirst);
    const monthMap = new Map<string, number>();
    oldestFirst.forEach((t, i) => {
      const d = new Date(t.transactionDate);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
      monthMap.set(key, balances[i]);
    });
    const points = Array.from(monthMap.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([month, value]) => {
        const [y, m] = month.split("-");
        return { label: `${y.slice(2)}/${m}`, value };
      });
    return points.slice(-12);
  })();

  const totalValue = assets.reduce((s, a) => s + a.currentValue, 0);
  const totalIncome = assets.reduce((s, a) => s + (a.monthlyIncome ?? 0), 0);

  return (
    <div className="flex flex-col h-[calc(100vh-1rem)]">
      {/* Header */}
      <div className="flex justify-between items-center px-6 pt-4 pb-3 shrink-0">
        <h2 className="text-2xl font-bold text-white">资产管理</h2>
        <button
          onClick={() => setShowForm(!showForm)}
          className="bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          {showForm ? "收起" : "+ 添加资产"}
        </button>
      </div>

      {showForm && (
        <div className="mx-6 mb-3 bg-neutral-900 border border-neutral-800 rounded-xl p-5 shrink-0">
          <AssetForm
            onSuccess={() => {
              setShowForm(false);
              fetchAssets(null);
            }}
          />
        </div>
      )}

      {/* Main content */}
      <div className="flex flex-1 gap-4 px-6 pb-4 min-h-0">
        {/* Left: list */}
        <div className="w-72 shrink-0 flex flex-col">
          <div className="grid grid-cols-2 gap-3 mb-3 shrink-0">
            <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-3">
              <p className="text-xs text-neutral-400">资产总值</p>
              <p className="text-base font-bold text-green-400 mt-0.5">
                {formatMoney(totalValue)}
              </p>
            </div>
            <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-3">
              <p className="text-xs text-neutral-400">月收入</p>
              <p className="text-base font-bold text-blue-400 mt-0.5">
                {formatMoney(totalIncome)}
              </p>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto space-y-1 bg-neutral-900 border border-neutral-800 rounded-xl p-2">
            {loading ? (
              <p className="text-center text-neutral-500 py-8 text-sm">
                加载中...
              </p>
            ) : assets.length === 0 ? (
              <p className="text-center text-neutral-500 py-8 text-sm">
                暂无资产
              </p>
            ) : (
              assets.map((a) => (
                <button
                  key={a.id}
                  onClick={() => handleSelect(a.id)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${
                    selectedId === a.id
                      ? "bg-blue-600/20 border border-blue-600/40"
                      : "hover:bg-neutral-800 border border-transparent"
                  }`}
                >
                  <div className="flex justify-between items-center">
                    <p className="text-sm font-medium text-white truncate">
                      {a.name}
                    </p>
                    <p className="text-sm font-bold text-green-400 ml-2 whitespace-nowrap">
                      {formatMoney(a.currentValue)}
                    </p>
                  </div>
                  <p className="text-xs text-neutral-500 mt-0.5">
                    {getAssetTypeLabel(a.type)}
                    {!a.isActive && " · 停用"}
                  </p>
                </button>
              ))
            )}
          </div>
        </div>

        {/* Right: detail */}
        <div className="flex-1 min-w-0 overflow-y-auto">
          {!selected ? (
            <div className="flex items-center justify-center h-full">
              <p className="text-neutral-500 text-sm">
                从左侧选择一项资产查看详情
              </p>
            </div>
          ) : (
            <>
              <div className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden">
                {/* 标题 + 账户操作 */}
                <div className="flex items-start justify-between gap-4 p-5">
                  <div className="min-w-0">
                    <h3 className="text-lg font-bold text-white truncate">
                      {selected.name}
                    </h3>
                    <p className="text-xs text-neutral-500 mt-1">
                      {getAssetTypeLabel(selected.type)} ·{" "}
                      {selected.isActive ? "启用" : "停用"}
                    </p>
                  </div>
                  <div className="flex gap-2 shrink-0">
                    <button
                      onClick={startEdit}
                      className="text-blue-400 hover:text-blue-300 text-xs border border-blue-900/50 hover:border-blue-800 rounded-lg px-3 py-1.5 transition-colors"
                    >
                      编辑
                    </button>
                    <button
                      onClick={() => setConfirmDelete(true)}
                      className="text-red-400 hover:text-red-300 text-xs border border-red-900/50 hover:border-red-800 rounded-lg px-3 py-1.5 transition-colors"
                    >
                      删除
                    </button>
                  </div>
                </div>

                {/* 基本信息 */}
                <div className="border-t border-neutral-800 p-5">
                  <h4 className="text-sm font-medium text-white mb-4">
                    基本信息
                  </h4>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-x-6 gap-y-4">
                    <Field
                      label="当前价值"
                      value={formatMoney(selected.currentValue)}
                      className="text-green-400"
                    />
                    <Field
                      label="类型"
                      value={getAssetTypeLabel(selected.type)}
                    />
                    <Field
                      label="月收入"
                      value={formatMoney(selected.monthlyIncome ?? 0)}
                      className="text-blue-400"
                    />
                    <Field
                      label="年化收益率"
                      value={`${(selected.annualYield ?? 0).toFixed(2)}%`}
                    />
                    <Field
                      label="收入频率"
                      value={
                        selected.incomeFrequency
                          ? getIncomeFrequencyLabel(selected.incomeFrequency)
                          : "-"
                      }
                    />
                    <Field
                      label="收入日"
                      value={
                        selected.incomeDay != null
                          ? `每月 ${selected.incomeDay} 号`
                          : "-"
                      }
                    />
                    <Field
                      label="状态"
                      value={selected.isActive ? "启用" : "停用"}
                      className={
                        selected.isActive ? "text-green-400" : "text-neutral-400"
                      }
                    />
                    <Field label="备注" value={selected.note || "-"} />
                  </div>
                </div>

                {/* 余额趋势 */}
                {chartData.length > 0 && (
                  <div className="border-t border-neutral-800 p-5">
                    <h4 className="text-sm font-medium text-white mb-3">
                      余额变动趋势
                    </h4>
                    <BalanceChart data={chartData} color="green" />
                  </div>
                )}

                {/* 交易明细 */}
                <div className="border-t border-neutral-800">
                  <div className="flex items-center justify-between px-5 py-3">
                    <h4 className="text-sm font-medium text-white">交易明细</h4>
                    {selectedTx && (
                      <span className="text-xs text-neutral-500">
                        已选中 1 条
                      </span>
                    )}
                  </div>

                  {visibleTxs.length === 0 ? (
                    <p className="text-center text-neutral-500 py-8 text-sm">
                      暂无交易记录
                    </p>
                  ) : (
                    <table className="w-full">
                      <thead>
                        <tr className="border-b border-neutral-800">
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            日期
                          </th>
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            类型
                          </th>
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            描述
                          </th>
                          <th className="text-right text-xs text-neutral-400 px-4 py-2">
                            金额
                          </th>
                          <th className="text-right text-xs text-neutral-400 px-4 py-2">
                            余额
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {visibleTxs.map((t) => (
                          <tr
                            key={t.id}
                            onClick={() =>
                              setSelectedTxId((cur) =>
                                cur === t.id ? null : t.id,
                              )
                            }
                            className={`border-b border-neutral-800/50 cursor-pointer transition-colors ${
                              selectedTxId === t.id
                                ? "bg-blue-600/15"
                                : "hover:bg-neutral-800/40"
                            }`}
                          >
                            <td className="px-4 py-2 text-xs text-neutral-400">
                              {formatDate(t.transactionDate)}
                              {t.isAutoGenerated && (
                                <span className="ml-1 text-neutral-600">
                                  自动
                                </span>
                              )}
                            </td>
                            <td className="px-4 py-2 text-xs text-neutral-400">
                              {txTypeLabel(t.type)}
                            </td>
                            <td className="px-4 py-2 text-xs text-white">
                              {t.description}
                            </td>
                            <td
                              className={`px-4 py-2 text-xs text-right font-medium ${
                                t.delta >= 0
                                  ? "text-green-400"
                                  : "text-red-400"
                              }`}
                            >
                              {t.delta >= 0 ? "+" : "-"}
                              {formatMoney(Math.abs(t.delta))}
                            </td>
                            <td className="px-4 py-2 text-xs text-right text-white font-medium">
                              {formatMoney(t.balance)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}

                  <Pagination
                    total={details[selected.id]?.length ?? 0}
                    page={currentPageNum}
                    totalPages={totalPages(selected.id)}
                    onChange={(p) =>
                      setTxPages((prev) => ({ ...prev, [selected.id]: p }))
                    }
                  />

                  {/* 明细操作 */}
                  <div className="flex items-center justify-between gap-3 px-5 py-3 border-t border-neutral-800">
                    <div className="flex gap-2">
                      <button
                        type="button"
                        disabled={!selectedTx}
                        onClick={() => selectedTx && setEditingTx(selectedTx)}
                        className="text-xs border border-neutral-700 rounded-lg px-3 py-1.5 text-neutral-300 hover:text-white hover:border-neutral-600 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                      >
                        编辑明细
                      </button>
                      <button
                        type="button"
                        disabled={!selectedTx}
                        onClick={() => setConfirmDeleteTx(true)}
                        className="text-xs border border-red-900/50 rounded-lg px-3 py-1.5 text-red-400 hover:text-red-300 hover:border-red-800 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                      >
                        删除明细
                      </button>
                    </div>
                    <button
                      type="button"
                      onClick={() => setShowTxForm(true)}
                      className="bg-green-600 hover:bg-green-700 text-white rounded-lg px-3 py-1.5 text-xs font-medium transition-colors"
                    >
                      + 记一笔
                    </button>
                  </div>
                </div>
              </div>

              {/* 账户删除确认 */}
              <ConfirmDialog
                open={confirmDelete}
                title="删除资产"
                message={
                  <>
                    确定删除「{selected.name}」？
                    <br />
                    若该资产已有交易记录，将改为停用而非彻底删除。
                  </>
                }
                loading={deleteLoading}
                onCancel={() => setConfirmDelete(false)}
                onConfirm={handleDeleteAccount}
              />

              {/* 明细删除确认 */}
              <ConfirmDialog
                open={confirmDeleteTx}
                title="删除明细"
                message="确定删除选中的这条明细吗？删除后该账户余额会按剩余流水同步调整。"
                loading={deleteTxLoading}
                onCancel={() => setConfirmDeleteTx(false)}
                onConfirm={handleDeleteTx}
              />

              {/* 记一笔 */}
              <Modal
                open={showTxForm}
                title="记一笔"
                onClose={() => setShowTxForm(false)}
              >
                <TransactionForm
                  preset={{
                    kind: "asset",
                    id: selected.id,
                    name: selected.name,
                  }}
                  onSuccess={async () => {
                    setShowTxForm(false);
                    await fetchAssets(selected.id);
                  }}
                />
              </Modal>

              {/* 编辑明细 */}
              <TransactionEditModal
                transaction={editingTx}
                onClose={() => setEditingTx(null)}
                onSaved={() => fetchAssets(selected.id)}
              />

              {/* 编辑账户基本信息 */}
              <Modal
                open={editing}
                title="编辑资产"
                onClose={() => setEditing(false)}
              >
                {editError && (
                  <div className="mb-3 p-3 bg-red-900/30 border border-red-800 rounded-lg text-red-400 text-sm">
                    {editError}
                  </div>
                )}
                <form onSubmit={handleEditSubmit} className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>名称</label>
                      <input
                        type="text"
                        required
                        value={editForm.name}
                        onChange={(e) =>
                          setEditForm({ ...editForm, name: e.target.value })
                        }
                        className={inputClass}
                      />
                    </div>
                    <div>
                      <label className={labelClass}>类型</label>
                      <select
                        value={editForm.type}
                        onChange={(e) =>
                          setEditForm({ ...editForm, type: e.target.value })
                        }
                        className={inputClass}
                      >
                        <option value="real_estate">房产</option>
                        <option value="deposit">存款</option>
                        <option value="investment">投资</option>
                        <option value="income_source">收入来源</option>
                        <option value="other">其他</option>
                      </select>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>当前价值 (元)</label>
                      <input
                        type="number"
                        step="0.01"
                        required
                        value={editForm.currentValue}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            currentValue: e.target.value,
                          })
                        }
                        className={inputClass}
                      />
                    </div>
                    <div>
                      <label className={labelClass}>月收入 (元)</label>
                      <input
                        type="number"
                        step="0.01"
                        value={editForm.monthlyIncome}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            monthlyIncome: e.target.value,
                          })
                        }
                        className={inputClass}
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>年化收益率 (%)</label>
                      <input
                        type="number"
                        step="0.01"
                        value={editForm.annualYield}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            annualYield: e.target.value,
                          })
                        }
                        className={inputClass}
                      />
                    </div>
                    <div>
                      <label className={labelClass}>收入频率</label>
                      <select
                        value={editForm.incomeFrequency}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            incomeFrequency: e.target.value,
                          })
                        }
                        className={inputClass}
                      >
                        <option value="monthly">每月</option>
                        <option value="quarterly">每季</option>
                        <option value="yearly">每年</option>
                        <option value="one_time">一次性</option>
                      </select>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>收入日</label>
                      <input
                        type="number"
                        min="1"
                        max="31"
                        value={editForm.incomeDay}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            incomeDay: e.target.value,
                          })
                        }
                        placeholder="每月几号"
                        className={inputClass}
                      />
                    </div>
                  </div>
                  <div>
                    <label className={labelClass}>备注</label>
                    <input
                      type="text"
                      value={editForm.note}
                      onChange={(e) =>
                        setEditForm({ ...editForm, note: e.target.value })
                      }
                      className={inputClass}
                    />
                  </div>
                  <button
                    type="submit"
                    disabled={editLoading}
                    className="w-full bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2.5 text-sm font-medium transition-colors disabled:opacity-50"
                  >
                    {editLoading ? "保存中..." : "保存修改"}
                  </button>
                </form>
              </Modal>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
