import { NextResponse } from "next/server";
import { db } from "@/db";
import { reconciliations, transactions } from "@/db/schema";
import { eq, and, desc } from "drizzle-orm";
import { requireUser } from "@/lib/auth";

export async function GET() {
  try {
    const user = await requireUser();
    const result = await db
      .select()
      .from(reconciliations)
      .where(eq(reconciliations.userId, user.id))
      .orderBy(desc(reconciliations.reconciliationDate));
    return NextResponse.json(result);
  } catch (e) {
    if ((e as Error).message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "请先登录" }, { status: 401 });
    }
    return NextResponse.json(
      { error: "获取对账记录失败" },
      { status: 500 }
    );
  }
}

export async function POST(request: Request) {
  try {
    const user = await requireUser();
    const body = await request.json();

    const difference = body.actualBalance - body.expectedBalance;

    const reconciliationResult = await db
      .insert(reconciliations)
      .values({
        userId: user.id,
        assetId: body.assetId ?? null,
        liabilityId: body.liabilityId ?? null,
        expectedBalance: body.expectedBalance,
        actualBalance: body.actualBalance,
        difference,
        reconciliationDate: new Date(body.reconciliationDate),
        note: body.note ?? null,
      });

    const reconciliationId = Number(reconciliationResult[0].insertId);
    const [reconciliation] = await db
      .select()
      .from(reconciliations)
      .where(eq(reconciliations.id, reconciliationId));

    if (Math.abs(difference) > 0.001) {
      const txType = body.assetId ? "asset_value_change" : "liability_principal_change";
      const txResult = await db
        .insert(transactions)
        .values({
          userId: user.id,
          type: txType,
          assetId: body.assetId ?? null,
          liabilityId: body.liabilityId ?? null,
          amount: difference,
          description: `对账调整: 预期 ${body.expectedBalance} -> 实际 ${body.actualBalance}`,
          transactionDate: new Date(body.reconciliationDate),
          isAutoGenerated: true,
          reconciliationId: reconciliation.id,
          note: `自动对账差额调整`,
        });

      const txInsertId = Number(txResult[0].insertId);
      const [tx] = await db
        .select()
        .from(transactions)
        .where(eq(transactions.id, txInsertId));

      await db
        .update(reconciliations)
        .set({ transactionId: tx.id })
        .where(eq(reconciliations.id, reconciliation.id));

      if (body.assetId) {
        const { assets } = await import("@/db/schema");
        await db
          .update(assets)
          .set({ currentValue: body.actualBalance, updatedAt: new Date() })
          .where(and(eq(assets.id, body.assetId), eq(assets.userId, user.id)));
      }

      if (body.liabilityId) {
        const { liabilities } = await import("@/db/schema");
        await db
          .update(liabilities)
          .set({ remainingPrincipal: body.actualBalance, updatedAt: new Date() })
          .where(and(eq(liabilities.id, body.liabilityId), eq(liabilities.userId, user.id)));
      }

      return NextResponse.json(
        { reconciliation, transaction: tx },
        { status: 201 }
      );
    }

    return NextResponse.json({ reconciliation, transaction: null }, { status: 201 });
  } catch (e) {
    if ((e as Error).message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "请先登录" }, { status: 401 });
    }
    return NextResponse.json(
      { error: "创建对账记录失败" },
      { status: 500 }
    );
  }
}
