import { NextResponse } from "next/server";
import { db } from "@/db";
import { reconciliations, transactions } from "@/db/schema";
import { eq, desc } from "drizzle-orm";

export async function GET() {
  try {
    const result = await db
      .select()
      .from(reconciliations)
      .orderBy(desc(reconciliations.reconciliationDate));
    return NextResponse.json(result);
  } catch {
    return NextResponse.json(
      { error: "获取对账记录失败" },
      { status: 500 }
    );
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const difference = body.actualBalance - body.expectedBalance;

    // 创建对账记录
    const reconciliationResult = await db
      .insert(reconciliations)
      .values({
        assetId: body.assetId ?? null,
        liabilityId: body.liabilityId ?? null,
        expectedBalance: body.expectedBalance,
        actualBalance: body.actualBalance,
        difference,
        reconciliationDate: new Date(body.reconciliationDate),
        note: body.note ?? null,
      })
      .returning();

    const reconciliation = reconciliationResult[0];

    // 如果有差异，自动创建一笔账目变动记录
    if (Math.abs(difference) > 0.001) {
      const txType = body.assetId ? "asset_value_change" : "liability_principal_change";
      const txResult = await db
        .insert(transactions)
        .values({
          type: txType,
          assetId: body.assetId ?? null,
          liabilityId: body.liabilityId ?? null,
          amount: difference,
          description: `对账调整: 预期 ${body.expectedBalance} -> 实际 ${body.actualBalance}`,
          transactionDate: new Date(body.reconciliationDate),
          isAutoGenerated: true,
          reconciliationId: reconciliation.id,
          note: `自动对账差额调整`,
        })
        .returning();

      // 更新对账记录中的 transactionId
      await db
        .update(reconciliations)
        .set({ transactionId: txResult[0].id })
        .where(eq(reconciliations.id, reconciliation.id));

      // 更新关联的资产或负债余额
      if (body.assetId) {
        const { assets } = await import("@/db/schema");
        await db
          .update(assets)
          .set({ currentValue: body.actualBalance, updatedAt: new Date() })
          .where(eq(assets.id, body.assetId));
      }

      if (body.liabilityId) {
        const { liabilities } = await import("@/db/schema");
        await db
          .update(liabilities)
          .set({ remainingPrincipal: body.actualBalance, updatedAt: new Date() })
          .where(eq(liabilities.id, body.liabilityId));
      }

      return NextResponse.json(
        { reconciliation, transaction: txResult[0] },
        { status: 201 }
      );
    }

    return NextResponse.json({ reconciliation, transaction: null }, { status: 201 });
  } catch {
    return NextResponse.json(
      { error: "创建对账记录失败" },
      { status: 500 }
    );
  }
}
