import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

// ========== 分类 ==========

export const categories = sqliteTable("categories", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  type: text("type", { enum: ["income", "expense", "asset", "liability"] }).notNull(),
  parentId: integer("parent_id"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
});

// ========== 资产 ==========

export const assets = sqliteTable("assets", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  type: text("type", {
    enum: ["real_estate", "deposit", "investment", "income_source", "other"],
  }).notNull(),
  categoryId: integer("category_id").references(() => categories.id),
  currentValue: real("current_value").notNull().default(0),
  // 现金流相关字段
  monthlyIncome: real("monthly_income").default(0),
  annualYield: real("annual_yield").default(0),
  // 收入来源特有字段
  incomeFrequency: text("income_frequency", {
    enum: ["monthly", "quarterly", "yearly", "one_time"],
  }),
  incomeDay: integer("income_day"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
});

// ========== 负债 ==========

export const liabilities = sqliteTable("liabilities", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  type: text("type", {
    enum: ["mortgage", "car_loan", "credit_card", "personal_loan", "other"],
  }).notNull(),
  categoryId: integer("category_id").references(() => categories.id),
  totalPrincipal: real("total_principal").notNull(),
  remainingPrincipal: real("remaining_principal").notNull(),
  annualRate: real("annual_rate").notNull().default(0),
  monthlyPayment: real("monthly_payment").notNull().default(0),
  paymentDay: integer("payment_day"),
  startDate: integer("start_date", { mode: "timestamp" }),
  endDate: integer("end_date", { mode: "timestamp" }),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
});

// ========== 账目变动记录 ==========

export const transactions = sqliteTable("transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  type: text("type", {
    enum: [
      "asset_value_change",
      "asset_income",
      "liability_repayment",
      "liability_principal_change",
      "expense",
      "income",
      "transfer",
      "reconciliation",
    ],
  }).notNull(),
  categoryId: integer("category_id").references(() => categories.id),
  assetId: integer("asset_id").references(() => assets.id),
  liabilityId: integer("liability_id").references(() => liabilities.id),
  amount: real("amount").notNull(),
  // 还款时区分本金和利息
  principalPart: real("principal_part").default(0),
  interestPart: real("interest_part").default(0),
  description: text("description").notNull(),
  transactionDate: integer("transaction_date", {
    mode: "timestamp",
  }).notNull(),
  isAutoGenerated: integer("is_auto_generated", { mode: "boolean" })
    .notNull()
    .default(false),
  reconciliationId: integer("reconciliation_id").references(
    () => reconciliations.id
  ),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
});

// ========== 对账记录 ==========

export const reconciliations = sqliteTable("reconciliations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  assetId: integer("asset_id").references(() => assets.id),
  liabilityId: integer("liability_id").references(() => liabilities.id),
  expectedBalance: real("expected_balance").notNull(),
  actualBalance: real("actual_balance").notNull(),
  difference: real("difference").notNull(),
  reconciliationDate: integer("reconciliation_date", {
    mode: "timestamp",
  }).notNull(),
  transactionId: integer("transaction_id"),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
});

// ========== 月度快照 ==========

export const monthlySnapshots = sqliteTable("monthly_snapshots", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  month: text("month").notNull(),
  totalAssets: real("total_assets").notNull().default(0),
  totalLiabilities: real("total_liabilities").notNull().default(0),
  netWorth: real("net_worth").notNull().default(0),
  monthlyCashFlow: real("monthly_cash_flow").notNull().default(0),
  assetBreakdown: text("asset_breakdown"),
  liabilityBreakdown: text("liability_breakdown"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date()
  ),
});
