import {
  sqliteTable,
  integer,
  text,
  real,
} from "drizzle-orm/sqlite-core";

// ========== 用户 ==========

export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  phone: text("phone").notNull().unique(),
  passwordHash: text("password_hash"),
  nickname: text("nickname"),
  wechatOpenid: text("wechat_openid").unique(),
  avatarUrl: text("avatar_url"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== 会话 ==========

export const sessions = sqliteTable("sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  token: text("token").notNull().unique(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== 分类 ==========

export const categories = sqliteTable("categories", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  name: text("name").notNull(),
  type: text("type").notNull(),
  parentId: integer("parent_id"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== 资产 ==========

export const assets = sqliteTable("assets", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  name: text("name").notNull(),
  type: text("type").notNull(),
  categoryId: integer("category_id").references(() => categories.id),
  currentValue: real("current_value").notNull().default(0),
  monthlyIncome: real("monthly_income").default(0),
  annualYield: real("annual_yield").default(0),
  incomeFrequency: text("income_frequency"),
  incomeDay: integer("income_day"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== 负债 ==========

export const liabilities = sqliteTable("liabilities", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  name: text("name").notNull(),
  type: text("type").notNull(),
  categoryId: integer("category_id").references(() => categories.id),
  totalPrincipal: real("total_principal").notNull(),
  remainingPrincipal: real("remaining_principal").notNull(),
  annualRate: real("annual_rate").notNull().default(0),
  repaymentMethod: text("repayment_method")
    .notNull()
    .default("equal_installment"),
  monthlyPayment: real("monthly_payment").notNull().default(0),
  paymentDay: integer("payment_day"),
  startDate: integer("start_date", { mode: "timestamp" }),
  endDate: integer("end_date", { mode: "timestamp" }),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== 账目变动记录 ==========

export const transactions = sqliteTable("transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  type: text("type").notNull(),
  categoryId: integer("category_id").references(() => categories.id),
  assetId: integer("asset_id").references(() => assets.id),
  liabilityId: integer("liability_id").references(() => liabilities.id),
  amount: real("amount").notNull(),
  principalPart: real("principal_part").default(0),
  interestPart: real("interest_part").default(0),
  description: text("description").notNull(),
  transactionDate: integer("transaction_date", { mode: "timestamp" }).notNull(),
  isAutoGenerated: integer("is_auto_generated", { mode: "boolean" })
    .notNull()
    .default(false),
  reconciliationId: integer("reconciliation_id").references(
    () => reconciliations.id,
  ),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== 对账记录 ==========

export const reconciliations = sqliteTable("reconciliations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  assetId: integer("asset_id").references(() => assets.id),
  liabilityId: integer("liability_id").references(() => liabilities.id),
  expectedBalance: real("expected_balance").notNull(),
  actualBalance: real("actual_balance").notNull(),
  difference: real("difference").notNull(),
  reconciliationDate: integer("reconciliation_date", {
    mode: "timestamp",
  }).notNull(),
  transactionId: integer("transaction_id"),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== AI 聊天会话 ==========

export const chatSessions = sqliteTable("chat_sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  title: text("title").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== AI 聊天消息 ==========

export const chatMessages = sqliteTable("chat_messages", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sessionId: integer("session_id")
    .notNull()
    .references(() => chatSessions.id, { onDelete: "cascade" }),
  role: text("role").notNull(),
  content: text("content").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});

// ========== 月度快照 ==========

export const monthlySnapshots = sqliteTable("monthly_snapshots", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  month: text("month").notNull(),
  totalAssets: real("total_assets").notNull().default(0),
  totalLiabilities: real("total_liabilities").notNull().default(0),
  netWorth: real("net_worth").notNull().default(0),
  monthlyCashFlow: real("monthly_cash_flow").notNull().default(0),
  assetBreakdown: text("asset_breakdown"),
  liabilityBreakdown: text("liability_breakdown"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});
