import {
  mysqlTable,
  int,
  varchar,
  text,
  double,
  datetime,
  boolean,
  serial,
} from "drizzle-orm/mysql-core";

// ========== 用户 ==========

export const users = mysqlTable("users", {
  id: serial("id").primaryKey(),
  phone: varchar("phone", { length: 20 }).notNull().unique(),
  passwordHash: varchar("password_hash", { length: 255 }),
  nickname: varchar("nickname", { length: 50 }),
  wechatOpenid: varchar("wechat_openid", { length: 100 }).unique(),
  avatarUrl: varchar("avatar_url", { length: 500 }),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
  updatedAt: datetime("updated_at").$defaultFn(() => new Date()),
});

// ========== 会话 ==========

export const sessions = mysqlTable("sessions", {
  id: serial("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  token: varchar("token", { length: 255 }).notNull().unique(),
  expiresAt: datetime("expires_at").notNull(),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
});

// ========== 分类 ==========

export const categories = mysqlTable("categories", {
  id: serial("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  name: varchar("name", { length: 100 }).notNull(),
  type: varchar("type", { length: 20 }).notNull(),
  parentId: int("parent_id"),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
});

// ========== 资产 ==========

export const assets = mysqlTable("assets", {
  id: serial("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  name: varchar("name", { length: 200 }).notNull(),
  type: varchar("type", { length: 20 }).notNull(),
  categoryId: int("category_id").references(() => categories.id),
  currentValue: double("current_value").notNull().default(0),
  monthlyIncome: double("monthly_income").default(0),
  annualYield: double("annual_yield").default(0),
  incomeFrequency: varchar("income_frequency", { length: 20 }),
  incomeDay: int("income_day"),
  isActive: boolean("is_active").notNull().default(true),
  note: text("note"),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
  updatedAt: datetime("updated_at").$defaultFn(() => new Date()),
});

// ========== 负债 ==========

export const liabilities = mysqlTable("liabilities", {
  id: serial("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  name: varchar("name", { length: 200 }).notNull(),
  type: varchar("type", { length: 20 }).notNull(),
  categoryId: int("category_id").references(() => categories.id),
  totalPrincipal: double("total_principal").notNull(),
  remainingPrincipal: double("remaining_principal").notNull(),
  annualRate: double("annual_rate").notNull().default(0),
  monthlyPayment: double("monthly_payment").notNull().default(0),
  paymentDay: int("payment_day"),
  startDate: datetime("start_date"),
  endDate: datetime("end_date"),
  isActive: boolean("is_active").notNull().default(true),
  note: text("note"),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
  updatedAt: datetime("updated_at").$defaultFn(() => new Date()),
});

// ========== 账目变动记录 ==========

export const transactions = mysqlTable("transactions", {
  id: serial("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  type: varchar("type", { length: 30 }).notNull(),
  categoryId: int("category_id").references(() => categories.id),
  assetId: int("asset_id").references(() => assets.id),
  liabilityId: int("liability_id").references(() => liabilities.id),
  amount: double("amount").notNull(),
  principalPart: double("principal_part").default(0),
  interestPart: double("interest_part").default(0),
  description: varchar("description", { length: 500 }).notNull(),
  transactionDate: datetime("transaction_date").notNull(),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  reconciliationId: int("reconciliation_id").references(
    () => reconciliations.id
  ),
  note: text("note"),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
});

// ========== 对账记录 ==========

export const reconciliations = mysqlTable("reconciliations", {
  id: serial("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  assetId: int("asset_id").references(() => assets.id),
  liabilityId: int("liability_id").references(() => liabilities.id),
  expectedBalance: double("expected_balance").notNull(),
  actualBalance: double("actual_balance").notNull(),
  difference: double("difference").notNull(),
  reconciliationDate: datetime("reconciliation_date").notNull(),
  transactionId: int("transaction_id"),
  note: text("note"),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
});

// ========== 月度快照 ==========

export const monthlySnapshots = mysqlTable("monthly_snapshots", {
  id: serial("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  month: varchar("month", { length: 7 }).notNull(),
  totalAssets: double("total_assets").notNull().default(0),
  totalLiabilities: double("total_liabilities").notNull().default(0),
  netWorth: double("net_worth").notNull().default(0),
  monthlyCashFlow: double("monthly_cash_flow").notNull().default(0),
  assetBreakdown: text("asset_breakdown"),
  liabilityBreakdown: text("liability_breakdown"),
  createdAt: datetime("created_at").$defaultFn(() => new Date()),
});
