"use client";

import { useState, useEffect } from "react";
import { LiabilityForm } from "@/components/Forms";
import {
  formatMoney,
  formatDate,
  getLiabilityTypeLabel,
  getRepaymentMethodLabel,
} from "@/lib/utils";

interface Liability {
  id: number;
  name: string;
  type: string;
  totalPrincipal: number;
  remainingPrincipal: number;
  annualRate: number;
  repaymentMethod: string;
  monthlyPayment: number;
  isActive: boolean;
  note: string | null;
}

interface Transaction {
  id: number;
  type: string;
  amount: number;
  principalPart: number;
  interestPart: number;
  description: string;
  transactionDate: string;
  isAutoGenerated: boolean;
}

export default function LiabilitiesPage() {
  const [liabilities, setLiabilities] = useState<Liability[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [details, setDetails] = useState<Record<number, Transaction[]>>({});

  useEffect(() => {
    let mounted = true;
    fetch("/api/liabilities")
      .then((r) => r.json())
      .then((data) => {
        if (mounted) {
          setLiabilities(data);
          setLoading(false);
        }
      });
    return () => {
      mounted = false;
    };
  }, []);

  const fetchLiabilities = () => {
    fetch("/api/liabilities")
      .then((r) => r.json())
      .then((data) => setLiabilities(data));
  };

  const handleDelete = async (id: number) => {
    if (!confirm("确定要删除这项负债吗？")) return;
    await fetch(`/api/liabilities?id=${id}`, { method: "DELETE" });
    fetchLiabilities();
  };

  const toggleDetails = async (liabilityId: number) => {
    if (expandedId === liabilityId) {
      setExpandedId(null);
      return;
    }
    setExpandedId(liabilityId);
    if (!details[liabilityId]) {
      const res = await fetch(`/api/transactions?liabilityId=${liabilityId}&limit=20`);
      const data = await res.json();
      setDetails((d) => ({ ...d, [liabilityId]: data }));
    }
  };

  const txTypeLabel = (type: string) => {
    const map: Record<string, string> = {
      liability_repayment: "还款",
      liability_principal_change: "借款",
    };
    return map[type] ?? type;
  };

  const totalRemaining = liabilities.reduce(
    (s, l) => s + l.remainingPrincipal,
    0
  );
  const totalPayment = liabilities.reduce((s, l) => s + l.monthlyPayment, 0);

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-white">负债管理</h2>
          <p className="text-sm text-neutral-400 mt-1">
            管理所有负债，追踪还款和利息
          </p>
        </div>
        <button
          onClick={() => setShowForm(!showForm)}
          className="bg-red-600 hover:bg-red-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          {showForm ? "收起" : "+ 添加负债"}
        </button>
      </div>

      {showForm && (
        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5">
          <LiabilityForm
            onSuccess={() => {
              fetchLiabilities();
              setShowForm(false);
            }}
          />
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
          <p className="text-sm text-neutral-400">负债总额</p>
          <p className="text-xl font-bold text-red-400 mt-1">
            {formatMoney(totalRemaining)}
          </p>
        </div>
        <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-4">
          <p className="text-sm text-neutral-400">月总还款</p>
          <p className="text-xl font-bold text-orange-400 mt-1">
            {formatMoney(totalPayment)}
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {loading ? (
          <div className="text-center text-neutral-500 py-8 text-sm">
            加载中...
          </div>
        ) : liabilities.length === 0 ? (
          <div className="text-center text-neutral-500 py-8 text-sm">
            暂无负债记录，点击上方按钮添加
          </div>
        ) : (
          liabilities.map((l) => (
            <div
              key={l.id}
              className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden"
            >
              <div
                className="flex items-center justify-between px-5 py-4 cursor-pointer hover:bg-neutral-800/30"
                onClick={() => toggleDetails(l.id)}
              >
                <div>
                  <p className="text-sm font-medium text-white">{l.name}</p>
                  <p className="text-xs text-neutral-500 mt-0.5">
                    {getLiabilityTypeLabel(l.type)} · {getRepaymentMethodLabel(l.repaymentMethod)}
                    {l.repaymentMethod !== "lump_sum" && l.monthlyPayment > 0 && (
                      <span className="ml-2">月还 {formatMoney(l.monthlyPayment)}</span>
                    )}
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  <div className="text-right">
                    <p className="text-sm font-bold text-red-400">
                      {formatMoney(l.remainingPrincipal)}
                    </p>
                    <p className="text-xs text-neutral-500">
                      利率 {l.annualRate.toFixed(2)}%
                    </p>
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDelete(l.id);
                    }}
                    className="text-red-400 hover:text-red-300 text-xs"
                  >
                    删除
                  </button>
                  <span
                    className={`text-neutral-500 text-xs transition-transform ${
                      expandedId === l.id ? "rotate-180" : ""
                    }`}
                  >
                    ▼
                  </span>
                </div>
              </div>

              {expandedId === l.id && (
                <div className="border-t border-neutral-800 px-5 py-3">
                  {details[l.id] ? (
                    details[l.id].length === 0 ? (
                      <p className="text-xs text-neutral-500 py-2">暂无交易记录</p>
                    ) : (
                      <table className="w-full">
                        <thead>
                          <tr>
                            <th className="text-left text-xs text-neutral-500 pb-2">日期</th>
                            <th className="text-left text-xs text-neutral-500 pb-2">类型</th>
                            <th className="text-left text-xs text-neutral-500 pb-2">描述</th>
                            <th className="text-right text-xs text-neutral-500 pb-2">金额</th>
                          </tr>
                        </thead>
                        <tbody>
                          {details[l.id].map((t) => (
                            <tr key={t.id} className="border-t border-neutral-800/50">
                              <td className="py-2 text-xs text-neutral-400">
                                {formatDate(t.transactionDate)}
                                {t.isAutoGenerated && (
                                  <span className="ml-1 text-neutral-600">自动</span>
                                )}
                              </td>
                              <td className="py-2 text-xs text-neutral-400">
                                {txTypeLabel(t.type)}
                              </td>
                              <td className="py-2 text-xs text-white">
                                {t.description}
                                {t.type === "liability_repayment" && t.principalPart > 0 && (
                                  <span className="text-neutral-500 ml-1">
                                    本金{formatMoney(t.principalPart)}+利息{formatMoney(t.interestPart)}
                                  </span>
                                )}
                              </td>
                              <td
                                className={`py-2 text-xs text-right font-medium ${
                                  t.type === "liability_principal_change"
                                    ? "text-orange-400"
                                    : "text-red-400"
                                }`}
                              >
                                {t.type === "liability_principal_change" ? "+" : "-"}
                                {formatMoney(Math.abs(t.amount))}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    )
                  ) : (
                    <p className="text-xs text-neutral-500 py-2">加载中...</p>
                  )}
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}
