"use client";

import { useState, useEffect, type ReactNode } from "react";
import { LiabilityForm, TransactionForm } from "@/components/Forms";
import { BalanceChart } from "@/components/BalanceChart";
import { Modal } from "@/components/Modal";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { TransactionEditModal } from "@/components/TransactionEditModal";
import { Pagination } from "@/components/Pagination";
import DatePicker from "@/components/DatePicker";
import {
  formatMoney,
  formatDate,
  getLiabilityTypeLabel,
  getRepaymentMethodLabel,
} from "@/lib/utils";
import { runningLiabilityBalances } from "@/lib/ledger";

interface Liability {
  id: number;
  name: string;
  type: string;
  totalPrincipal: number;
  remainingPrincipal: number;
  annualRate: number;
  repaymentMethod: string;
  monthlyPayment: number;
  paymentDay: number | null;
  startDate: string | null;
  endDate: string | null;
  isActive: boolean;
  note: string | null;
}

interface Transaction {
  id: number;
  type: string;
  amount: number;
  principalPart: number;
  interestPart: number;
  description: string;
  transactionDate: string;
  isAutoGenerated: boolean;
  note: string | null;
}

const inputClass =
  "w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500";
const labelClass = "block text-sm text-neutral-400 mb-1";

function Field({
  label,
  value,
  className,
}: {
  label: string;
  value: ReactNode;
  className?: string;
}) {
  return (
    <div className="min-w-0">
      <p className="text-xs text-neutral-500">{label}</p>
      <p className={`text-sm font-medium mt-1 break-words ${className ?? "text-white"}`}>
        {value}
      </p>
    </div>
  );
}

function calcMonthlyPayment(
  principal: number,
  annualRate: number,
  method: string,
  months?: number,
): number {
  if (!principal || principal <= 0) return 0;
  const r = annualRate / 100 / 12;
  const n = months ?? 12;

  if (method === "equal_installment") {
    if (r === 0) return principal / n;
    return (principal * r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1);
  }
  if (method === "interest_only") {
    return principal * r;
  }
  return 0;
}

export default function LiabilitiesPage() {
  const [liabilities, setLiabilities] = useState<Liability[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [details, setDetails] = useState<Record<number, Transaction[]>>({});
  const [txPages, setTxPages] = useState<Record<number, number>>({});
  const txLimit = 20;
  const [selectedTxId, setSelectedTxId] = useState<number | null>(null);

  // 账户基本信息编辑
  const [editing, setEditing] = useState(false);
  const [editError, setEditError] = useState("");
  const [editLoading, setEditLoading] = useState(false);
  const [editCalcMonths, setEditCalcMonths] = useState("12");
  const [editForm, setEditForm] = useState({
    name: "",
    type: "mortgage",
    totalPrincipal: "",
    remainingPrincipal: "",
    annualRate: "",
    repaymentMethod: "equal_installment",
    monthlyPayment: "",
    paymentDay: "",
    startDate: "",
    note: "",
  });

  // 弹窗状态
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deleteLoading, setDeleteLoading] = useState(false);
  const [showTxForm, setShowTxForm] = useState(false);
  const [editingTx, setEditingTx] = useState<Transaction | null>(null);
  const [confirmDeleteTx, setConfirmDeleteTx] = useState(false);
  const [deleteTxLoading, setDeleteTxLoading] = useState(false);

  const loadDetails = async (liabilityId: number) => {
    const res = await fetch(
      `/api/transactions?liabilityId=${liabilityId}&all=1`,
    );
    const result = await res.json();
    setDetails((d) => ({ ...d, [liabilityId]: result.data ?? [] }));
    setTxPages((p) => ({ ...p, [liabilityId]: 1 }));
  };

  // 重新拉取账户列表，并同步刷新当前选中账户的明细
  const fetchLiabilities = async (preferId?: number | null) => {
    const res = await fetch("/api/liabilities");
    const data = await res.json();
    const list: Liability[] = Array.isArray(data) ? data : [];
    setLiabilities(list);
    setLoading(false);
    const wanted = preferId ?? selectedId;
    const nextId =
      wanted && list.some((l) => l.id === wanted)
        ? wanted
        : list[0]?.id ?? null;
    setSelectedId(nextId);
    if (nextId) await loadDetails(nextId);
  };

  useEffect(() => {
    let mounted = true;
    fetch("/api/liabilities")
      .then((r) => r.json())
      .then((data) => {
        if (!mounted) return;
        const list: Liability[] = Array.isArray(data) ? data : [];
        setLiabilities(list);
        setLoading(false);
        if (list.length > 0) {
          setSelectedId(list[0].id);
          loadDetails(list[0].id);
        }
      });
    return () => {
      mounted = false;
    };
  }, []);

  const handleSelect = (id: number) => {
    setSelectedId(id);
    setSelectedTxId(null);
    loadDetails(id);
  };

  const startEdit = () => {
    if (!selected) return;
    setEditError("");
    // 如果有起始日期和结束日期，计算总期数
    let totalMonths = "12";
    if (selected.startDate && selected.endDate) {
      const start = new Date(selected.startDate);
      const end = new Date(selected.endDate);
      const months =
        (end.getFullYear() - start.getFullYear()) * 12 +
        (end.getMonth() - start.getMonth());
      if (months > 0) totalMonths = String(months);
    }
    setEditCalcMonths(totalMonths);
    setEditForm({
      name: selected.name,
      type: selected.type,
      totalPrincipal: String(selected.totalPrincipal),
      remainingPrincipal: String(selected.remainingPrincipal),
      annualRate: String(selected.annualRate),
      repaymentMethod: selected.repaymentMethod,
      monthlyPayment: String(selected.monthlyPayment),
      paymentDay:
        selected.paymentDay != null ? String(selected.paymentDay) : "",
      startDate: selected.startDate ? selected.startDate.slice(0, 10) : "",
      note: selected.note ?? "",
    });
    setEditing(true);
  };

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selected) return;
    setEditLoading(true);
    setEditError("");
    try {
      const res = await fetch("/api/liabilities", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: selected.id,
          name: editForm.name,
          type: editForm.type,
          totalPrincipal: Number(editForm.totalPrincipal),
          remainingPrincipal: Number(editForm.remainingPrincipal),
          annualRate: Number(editForm.annualRate),
          repaymentMethod: editForm.repaymentMethod,
          monthlyPayment: Number(editForm.monthlyPayment),
          paymentDay: editForm.paymentDay ? Number(editForm.paymentDay) : null,
          startDate: editForm.startDate
            ? new Date(editForm.startDate).toISOString()
            : null,
          note: editForm.note || null,
        }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        setEditError(data.error || "保存失败");
        return;
      }
      setEditing(false);
      await fetchLiabilities(selected.id);
    } finally {
      setEditLoading(false);
    }
  };

  const handleCalcCashFlow = () => {
    const principal = Number(
      editForm.remainingPrincipal || editForm.totalPrincipal,
    );
    const rate = Number(editForm.annualRate);
    if (!principal || principal <= 0) return;

    // 根据起始日期和总期数计算剩余期数
    let months = Number(editCalcMonths) || 12;
    if (editForm.startDate) {
      const start = new Date(editForm.startDate);
      const now = new Date();
      const elapsed =
        (now.getFullYear() - start.getFullYear()) * 12 +
        (now.getMonth() - start.getMonth());
      const remaining = months - elapsed;
      if (remaining > 0) months = remaining;
      else months = 1; // 至少1期
    }

    const payment = calcMonthlyPayment(
      principal,
      rate,
      editForm.repaymentMethod,
      months,
    );
    setEditForm((f) => ({
      ...f,
      monthlyPayment: String(Math.round(payment * 100) / 100),
    }));
  };

  const handleDeleteAccount = async () => {
    if (!selected) return;
    setDeleteLoading(true);
    try {
      await fetch(`/api/liabilities?id=${selected.id}`, { method: "DELETE" });
      setConfirmDelete(false);
      setSelectedTxId(null);
      await fetchLiabilities(null);
    } finally {
      setDeleteLoading(false);
    }
  };

  const handleDeleteTx = async () => {
    if (!selectedTx) return;
    setDeleteTxLoading(true);
    try {
      await fetch(`/api/transactions?id=${selectedTx.id}`, {
        method: "DELETE",
      });
      setConfirmDeleteTx(false);
      setSelectedTxId(null);
      await fetchLiabilities(selectedId);
    } finally {
      setDeleteTxLoading(false);
    }
  };

  const totalPages = (id: number) =>
    Math.max(1, Math.ceil((details[id]?.length ?? 0) / txLimit));
  const currentPage = (id: number) => txPages[id] ?? 1;

  const txTypeLabel = (type: string) => {
    const map: Record<string, string> = {
      liability_repayment: "还款",
      liability_principal_change: "借款",
    };
    return map[type] ?? type;
  };

  const selected = liabilities.find((l) => l.id === selectedId);
  const selectedTxs = selectedId ? details[selectedId] ?? null : null;

  // 以流水为准：按时间从旧到新重放完整流水，得到每一笔之后的余额
  const txsWithBalance = (() => {
    if (!selectedTxs || selectedTxs.length === 0) return [];
    const oldestFirst = [...selectedTxs].reverse();
    const balances = runningLiabilityBalances(oldestFirst);
    const balanceById = new Map<number, number>();
    oldestFirst.forEach((t, i) => balanceById.set(t.id, balances[i]));
    return selectedTxs.map((t) => ({
      ...t,
      balance: balanceById.get(t.id) ?? 0,
    }));
  })();

  const currentPageNum = selectedId ? currentPage(selectedId) : 1;
  const visibleTxs = txsWithBalance.slice(
    (currentPageNum - 1) * txLimit,
    currentPageNum * txLimit,
  );
  const selectedTx =
    txsWithBalance.find((t) => t.id === selectedTxId) ?? null;

  // Monthly chart data（同样基于完整流水）
  const chartData = (() => {
    if (!selectedTxs || selectedTxs.length === 0) return [];
    const oldestFirst = [...selectedTxs].reverse();
    const balances = runningLiabilityBalances(oldestFirst);
    const monthMap = new Map<string, number>();
    oldestFirst.forEach((t, i) => {
      const d = new Date(t.transactionDate);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
      monthMap.set(key, balances[i]);
    });
    const points = Array.from(monthMap.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([month, value]) => {
        const [y, m] = month.split("-");
        return { label: `${y.slice(2)}/${m}`, value };
      });
    return points.slice(-12);
  })();

  const repaidPercent =
    selected && selected.totalPrincipal > 0
      ? Math.min(
          100,
          ((selected.totalPrincipal - selected.remainingPrincipal) /
            selected.totalPrincipal) *
            100,
        )
      : 0;

  const totalRemaining = liabilities.reduce(
    (s, l) => s + l.remainingPrincipal,
    0,
  );
  const totalPayment = liabilities.reduce((s, l) => s + l.monthlyPayment, 0);

  return (
    <div className="flex flex-col h-[calc(100vh-1rem)]">
      {/* Header */}
      <div className="flex justify-between items-center px-6 pt-4 pb-3 shrink-0">
        <h2 className="text-2xl font-bold text-white">负债管理</h2>
        <button
          onClick={() => setShowForm(!showForm)}
          className="bg-red-600 hover:bg-red-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          {showForm ? "收起" : "+ 添加负债"}
        </button>
      </div>

      {showForm && (
        <div className="mx-6 mb-3 bg-neutral-900 border border-neutral-800 rounded-xl p-5 shrink-0">
          <LiabilityForm
            onSuccess={() => {
              setShowForm(false);
              fetchLiabilities(null);
            }}
          />
        </div>
      )}

      {/* Main content */}
      <div className="flex flex-1 gap-4 px-6 pb-4 min-h-0">
        {/* Left: list */}
        <div className="w-72 shrink-0 flex flex-col">
          <div className="grid grid-cols-2 gap-3 mb-3 shrink-0">
            <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-3">
              <p className="text-xs text-neutral-400">负债总额</p>
              <p className="text-base font-bold text-red-400 mt-0.5">
                {formatMoney(totalRemaining)}
              </p>
            </div>
            <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-3">
              <p className="text-xs text-neutral-400">月还款</p>
              <p className="text-base font-bold text-orange-400 mt-0.5">
                {formatMoney(totalPayment)}
              </p>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto space-y-1 bg-neutral-900 border border-neutral-800 rounded-xl p-2">
            {loading ? (
              <p className="text-center text-neutral-500 py-8 text-sm">
                加载中...
              </p>
            ) : liabilities.length === 0 ? (
              <p className="text-center text-neutral-500 py-8 text-sm">
                暂无负债
              </p>
            ) : (
              liabilities.map((l) => (
                <button
                  key={l.id}
                  onClick={() => handleSelect(l.id)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${
                    selectedId === l.id
                      ? "bg-red-600/20 border border-red-600/40"
                      : "hover:bg-neutral-800 border border-transparent"
                  }`}
                >
                  <div className="flex justify-between items-center">
                    <p className="text-sm font-medium text-white truncate">
                      {l.name}
                    </p>
                    <p className="text-sm font-bold text-red-400 ml-2 whitespace-nowrap">
                      {formatMoney(l.remainingPrincipal)}
                    </p>
                  </div>
                  <p className="text-xs text-neutral-500 mt-0.5">
                    {getLiabilityTypeLabel(l.type)}
                    {!l.isActive && " · 已结清"}
                  </p>
                </button>
              ))
            )}
          </div>
        </div>

        {/* Right: detail */}
        <div className="flex-1 min-w-0 overflow-y-auto">
          {!selected ? (
            <div className="flex items-center justify-center h-full">
              <p className="text-neutral-500 text-sm">
                从左侧选择一项负债查看详情
              </p>
            </div>
          ) : (
            <>
              <div className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden">
                {/* 标题 + 账户操作 */}
                <div className="flex items-start justify-between gap-4 p-5">
                  <div className="min-w-0">
                    <h3 className="text-lg font-bold text-white truncate">
                      {selected.name}
                    </h3>
                    <p className="text-xs text-neutral-500 mt-1">
                      {getLiabilityTypeLabel(selected.type)} ·{" "}
                      {selected.isActive ? "还款中" : "已结清"}
                    </p>
                  </div>
                  <div className="flex gap-2 shrink-0">
                    <button
                      onClick={startEdit}
                      className="text-blue-400 hover:text-blue-300 text-xs border border-blue-900/50 hover:border-blue-800 rounded-lg px-3 py-1.5 transition-colors"
                    >
                      编辑
                    </button>
                    <button
                      onClick={() => setConfirmDelete(true)}
                      className="text-red-400 hover:text-red-300 text-xs border border-red-900/50 hover:border-red-800 rounded-lg px-3 py-1.5 transition-colors"
                    >
                      删除
                    </button>
                  </div>
                </div>

                {/* 基本信息 */}
                <div className="border-t border-neutral-800 p-5">
                  <h4 className="text-sm font-medium text-white mb-4">
                    基本信息
                  </h4>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-x-6 gap-y-4">
                    <Field
                      label="剩余本金"
                      value={formatMoney(selected.remainingPrincipal)}
                      className="text-red-400"
                    />
                    <Field
                      label="总本金"
                      value={formatMoney(selected.totalPrincipal)}
                    />
                    <Field
                      label="年利率"
                      value={`${selected.annualRate.toFixed(2)}%`}
                    />
                    <Field
                      label={
                        selected.repaymentMethod === "lump_sum"
                          ? "到期还款"
                          : "月还款"
                      }
                      value={
                        selected.repaymentMethod === "lump_sum"
                          ? "-"
                          : formatMoney(selected.monthlyPayment)
                      }
                      className="text-orange-400"
                    />
                    <Field
                      label="还款方式"
                      value={getRepaymentMethodLabel(selected.repaymentMethod)}
                    />
                    <Field
                      label="还款日"
                      value={
                        selected.paymentDay != null
                          ? `每月 ${selected.paymentDay} 号`
                          : "-"
                      }
                    />
                    <Field
                      label="起始日期"
                      value={
                        selected.startDate
                          ? formatDate(selected.startDate)
                          : "-"
                      }
                    />
                    <Field
                      label="状态"
                      value={selected.isActive ? "还款中" : "已结清"}
                      className={
                        selected.isActive ? "text-orange-400" : "text-neutral-400"
                      }
                    />
                    <Field label="备注" value={selected.note || "-"} />
                  </div>
                </div>

                {/* 还款进度 */}
                <div className="border-t border-neutral-800 p-5">
                  <div className="flex justify-between text-xs text-neutral-400 mb-2">
                    <span>还款进度</span>
                    <span>{repaidPercent.toFixed(1)}% 已还</span>
                  </div>
                  <div className="w-full bg-neutral-800 rounded-full h-2">
                    <div
                      className="bg-green-500 h-2 rounded-full transition-all"
                      style={{ width: `${repaidPercent}%` }}
                    />
                  </div>
                  <div className="flex justify-between text-xs text-neutral-500 mt-1.5">
                    <span>
                      已还{" "}
                      {formatMoney(
                        selected.totalPrincipal - selected.remainingPrincipal,
                      )}
                    </span>
                    <span>剩余 {formatMoney(selected.remainingPrincipal)}</span>
                  </div>
                </div>

                {/* 余额趋势 */}
                {chartData.length > 0 && (
                  <div className="border-t border-neutral-800 p-5">
                    <h4 className="text-sm font-medium text-white mb-3">
                      余额变动趋势
                    </h4>
                    <BalanceChart data={chartData} color="red" />
                  </div>
                )}

                {/* 交易明细 */}
                <div className="border-t border-neutral-800">
                  <div className="flex items-center justify-between px-5 py-3">
                    <h4 className="text-sm font-medium text-white">交易明细</h4>
                    {selectedTx && (
                      <span className="text-xs text-neutral-500">
                        已选中 1 条
                      </span>
                    )}
                  </div>

                  {visibleTxs.length === 0 ? (
                    <p className="text-center text-neutral-500 py-8 text-sm">
                      暂无交易记录
                    </p>
                  ) : (
                    <table className="w-full">
                      <thead>
                        <tr className="border-b border-neutral-800">
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            日期
                          </th>
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            类型
                          </th>
                          <th className="text-left text-xs text-neutral-400 px-4 py-2">
                            描述
                          </th>
                          <th className="text-right text-xs text-neutral-400 px-4 py-2">
                            金额
                          </th>
                          <th className="text-right text-xs text-neutral-400 px-4 py-2">
                            余额
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {visibleTxs.map((t) => (
                          <tr
                            key={t.id}
                            onClick={() =>
                              setSelectedTxId((cur) =>
                                cur === t.id ? null : t.id,
                              )
                            }
                            className={`border-b border-neutral-800/50 cursor-pointer transition-colors ${
                              selectedTxId === t.id
                                ? "bg-red-600/15"
                                : "hover:bg-neutral-800/40"
                            }`}
                          >
                            <td className="px-4 py-2 text-xs text-neutral-400">
                              {formatDate(t.transactionDate)}
                              {t.isAutoGenerated && (
                                <span className="ml-1 text-neutral-600">
                                  自动
                                </span>
                              )}
                            </td>
                            <td className="px-4 py-2 text-xs text-neutral-400">
                              {txTypeLabel(t.type)}
                            </td>
                            <td className="px-4 py-2 text-xs text-white">
                              {t.description}
                              {t.type === "liability_repayment" &&
                                t.principalPart > 0 && (
                                  <span className="text-neutral-500 ml-1">
                                    本{formatMoney(t.principalPart)}+息
                                    {formatMoney(t.interestPart)}
                                  </span>
                                )}
                            </td>
                            <td
                              className={`px-4 py-2 text-xs text-right font-medium ${
                                t.type === "liability_principal_change"
                                  ? "text-orange-400"
                                  : "text-red-400"
                              }`}
                            >
                              {t.type === "liability_principal_change"
                                ? "+"
                                : "-"}
                              {formatMoney(Math.abs(t.amount))}
                            </td>
                            <td className="px-4 py-2 text-xs text-right text-white font-medium">
                              {formatMoney(t.balance)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}

                  <Pagination
                    total={details[selected.id]?.length ?? 0}
                    page={currentPageNum}
                    totalPages={totalPages(selected.id)}
                    onChange={(p) =>
                      setTxPages((prev) => ({ ...prev, [selected.id]: p }))
                    }
                  />

                  {/* 明细操作 */}
                  <div className="flex items-center justify-between gap-3 px-5 py-3 border-t border-neutral-800">
                    <div className="flex gap-2">
                      <button
                        type="button"
                        disabled={!selectedTx}
                        onClick={() => selectedTx && setEditingTx(selectedTx)}
                        className="text-xs border border-neutral-700 rounded-lg px-3 py-1.5 text-neutral-300 hover:text-white hover:border-neutral-600 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                      >
                        编辑明细
                      </button>
                      <button
                        type="button"
                        disabled={!selectedTx}
                        onClick={() => setConfirmDeleteTx(true)}
                        className="text-xs border border-red-900/50 rounded-lg px-3 py-1.5 text-red-400 hover:text-red-300 hover:border-red-800 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                      >
                        删除明细
                      </button>
                    </div>
                    <button
                      type="button"
                      onClick={() => setShowTxForm(true)}
                      className="bg-green-600 hover:bg-green-700 text-white rounded-lg px-3 py-1.5 text-xs font-medium transition-colors"
                    >
                      + 记一笔
                    </button>
                  </div>
                </div>
              </div>

              {/* 账户删除确认 */}
              <ConfirmDialog
                open={confirmDelete}
                title="删除负债"
                message={
                  <>
                    确定删除「{selected.name}」？
                    <br />
                    若该负债已有交易记录，将改为停用而非彻底删除。
                  </>
                }
                loading={deleteLoading}
                onCancel={() => setConfirmDelete(false)}
                onConfirm={handleDeleteAccount}
              />

              {/* 明细删除确认 */}
              <ConfirmDialog
                open={confirmDeleteTx}
                title="删除明细"
                message="确定删除选中的这条明细吗？删除后该账户余额会按剩余流水同步调整。"
                loading={deleteTxLoading}
                onCancel={() => setConfirmDeleteTx(false)}
                onConfirm={handleDeleteTx}
              />

              {/* 记一笔 */}
              <Modal
                open={showTxForm}
                title="记一笔"
                onClose={() => setShowTxForm(false)}
              >
                <TransactionForm
                  preset={{
                    kind: "liability",
                    id: selected.id,
                    name: selected.name,
                  }}
                  onSuccess={async () => {
                    setShowTxForm(false);
                    await fetchLiabilities(selected.id);
                  }}
                />
              </Modal>

              {/* 编辑明细 */}
              <TransactionEditModal
                transaction={editingTx}
                onClose={() => setEditingTx(null)}
                onSaved={() => fetchLiabilities(selected.id)}
              />

              {/* 编辑账户基本信息 */}
              <Modal
                open={editing}
                title="编辑负债"
                onClose={() => setEditing(false)}
              >
                {editError && (
                  <div className="mb-3 p-3 bg-red-900/30 border border-red-800 rounded-lg text-red-400 text-sm">
                    {editError}
                  </div>
                )}
                <form onSubmit={handleEditSubmit} className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>名称</label>
                      <input
                        type="text"
                        required
                        value={editForm.name}
                        onChange={(e) =>
                          setEditForm({ ...editForm, name: e.target.value })
                        }
                        className={inputClass}
                      />
                    </div>
                    <div>
                      <label className={labelClass}>类型</label>
                      <select
                        value={editForm.type}
                        onChange={(e) =>
                          setEditForm({ ...editForm, type: e.target.value })
                        }
                        className={inputClass}
                      >
                        <option value="mortgage">房贷</option>
                        <option value="car_loan">车贷</option>
                        <option value="credit_card">信用卡</option>
                        <option value="personal_loan">个人贷款</option>
                        <option value="other">其他</option>
                      </select>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>总本金 (元)</label>
                      <input
                        type="number"
                        step="0.01"
                        required
                        value={editForm.totalPrincipal}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            totalPrincipal: e.target.value,
                          })
                        }
                        className={inputClass}
                      />
                    </div>
                    <div>
                      <label className={labelClass}>剩余本金 (元)</label>
                      <input
                        type="number"
                        step="0.01"
                        required
                        value={editForm.remainingPrincipal}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            remainingPrincipal: e.target.value,
                          })
                        }
                        className={inputClass}
                      />
                    </div>
                  </div>
                  <div>
                    <label className={labelClass}>还款方式</label>
                    <select
                      value={editForm.repaymentMethod}
                      onChange={(e) =>
                        setEditForm({
                          ...editForm,
                          repaymentMethod: e.target.value,
                        })
                      }
                      className={inputClass}
                    >
                      <option value="equal_installment">等额本息</option>
                      <option value="interest_only">按月付息到期还本</option>
                      <option value="lump_sum">一次性到期还本付息</option>
                    </select>
                  </div>
                  {editForm.repaymentMethod !== "lump_sum" && (
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className={labelClass}>起始日期</label>
                        <DatePicker
                          value={editForm.startDate}
                          onChange={(v) =>
                            setEditForm({ ...editForm, startDate: v })
                          }
                          placeholder="选择起始日期"
                          className="py-2"
                        />
                      </div>
                      <div>
                        <label className={labelClass}>总期数 (月)</label>
                        <input
                          type="number"
                          min="1"
                          value={editCalcMonths}
                          onChange={(e) => setEditCalcMonths(e.target.value)}
                          className={inputClass}
                          placeholder="如: 360"
                        />
                      </div>
                    </div>
                  )}
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>年利率 (%)</label>
                      <input
                        type="number"
                        step="0.01"
                        value={editForm.annualRate}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            annualRate: e.target.value,
                          })
                        }
                        className={inputClass}
                      />
                    </div>
                    <div>
                      <label className={labelClass}>
                        {editForm.repaymentMethod === "lump_sum"
                          ? "到期总还款"
                          : "月还款"}{" "}
                        (元)
                      </label>
                      <input
                        type="number"
                        step="0.01"
                        value={editForm.monthlyPayment}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            monthlyPayment: e.target.value,
                          })
                        }
                        className={inputClass}
                        disabled={editForm.repaymentMethod === "lump_sum"}
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className={labelClass}>还款日</label>
                      <input
                        type="number"
                        min="1"
                        max="31"
                        value={editForm.paymentDay}
                        onChange={(e) =>
                          setEditForm({
                            ...editForm,
                            paymentDay: e.target.value,
                          })
                        }
                        placeholder="每月几号"
                        className={inputClass}
                      />
                    </div>
                  </div>
                  {editForm.repaymentMethod !== "lump_sum" && (
                    <div className="text-xs text-neutral-500">
                      基于起始日期和总期数，自动计算剩余{" "}
                      <strong className="text-white">
                        {(() => {
                          const total = Number(editCalcMonths) || 12;
                          if (!editForm.startDate) return String(total);
                          const start = new Date(editForm.startDate);
                          const now = new Date();
                          const elapsed =
                            (now.getFullYear() - start.getFullYear()) * 12 +
                            (now.getMonth() - start.getMonth());
                          return String(Math.max(1, total - elapsed));
                        })()}
                      </strong>{" "}
                      期
                      <button
                        type="button"
                        onClick={handleCalcCashFlow}
                        className="ml-3 text-emerald-400 hover:text-emerald-300 border border-emerald-900/50 hover:border-emerald-800 rounded-lg px-3 py-1 transition-colors"
                      >
                        计算现金流
                      </button>
                    </div>
                  )}
                  <div>
                    <label className={labelClass}>备注</label>
                    <input
                      type="text"
                      value={editForm.note}
                      onChange={(e) =>
                        setEditForm({ ...editForm, note: e.target.value })
                      }
                      className={inputClass}
                    />
                  </div>
                  <button
                    type="submit"
                    disabled={editLoading}
                    className="w-full bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2.5 text-sm font-medium transition-colors disabled:opacity-50"
                  >
                    {editLoading ? "保存中..." : "保存修改"}
                  </button>
                </form>
              </Modal>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
