"use client";

import { useState, useEffect } from "react";
import { TransactionForm } from "@/components/Forms";
import {
  formatMoney,
  formatDate,
  getTransactionTypeLabel,
} from "@/lib/utils";

interface Transaction {
  id: number;
  type: string;
  amount: number;
  principalPart: number;
  interestPart: number;
  description: string;
  transactionDate: string;
  isAutoGenerated: boolean;
  note: string | null;
}

export default function TransactionsPage() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [showModal, setShowModal] = useState(false);
  const [loading, setLoading] = useState(true);
  const [typeFilter, setTypeFilter] = useState("");
  const [refreshKey, setRefreshKey] = useState(0);
  const [editingTx, setEditingTx] = useState<Transaction | null>(null);
  const [editForm, setEditForm] = useState({
    amount: "",
    principalPart: "",
    interestPart: "",
    description: "",
    transactionDate: "",
    note: "",
  });
  const [editLoading, setEditLoading] = useState(false);
  useEffect(() => {
    let mounted = true;
    const params = new URLSearchParams();
    if (typeFilter) params.set("type", typeFilter);
    fetch(`/api/transactions?${params}`)
      .then((r) => r.json())
      .then((data) => {
        if (mounted) {
          setTransactions(data);
          setLoading(false);
        }
      });
    return () => {
      mounted = false;
    };
  }, [typeFilter, refreshKey]);

  const fetchTransactions = () => setRefreshKey((k) => k + 1);

  const handleDelete = async (id: number) => {
    if (!confirm("确定要删除这条记录吗？")) return;
    await fetch(`/api/transactions?id=${id}`, { method: "DELETE" });
    fetchTransactions();
  };

  const startEdit = (t: Transaction) => {
    setEditingTx(t);
    setEditForm({
      amount: String(t.amount),
      principalPart: t.principalPart ? String(t.principalPart) : "",
      interestPart: t.interestPart ? String(t.interestPart) : "",
      description: t.description,
      transactionDate: t.transactionDate.slice(0, 10),
      note: t.note ?? "",
    });
  };

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingTx) return;
    setEditLoading(true);
    try {
      await fetch("/api/transactions", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: editingTx.id,
          amount: Number(editForm.amount),
          principalPart: editForm.principalPart ? Number(editForm.principalPart) : 0,
          interestPart: editForm.interestPart ? Number(editForm.interestPart) : 0,
          description: editForm.description,
          transactionDate: editForm.transactionDate,
          note: editForm.note || null,
        }),
      });
      setEditingTx(null);
      fetchTransactions();
    } finally {
      setEditLoading(false);
    }
  };
  const typeColor = (type: string) => {
    if (["income", "asset_income"].includes(type)) return "text-green-400";
    if (["expense", "liability_repayment"].includes(type)) return "text-red-400";
    return "text-blue-400";
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-white">记账</h2>
          <p className="text-sm text-neutral-400 mt-1">
            记录收支和资产负债变动
          </p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="bg-green-600 hover:bg-green-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          + 记一笔
        </button>
      </div>

      {/* Modal */}
      {showModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60"
          onClick={(e) => {
            if (e.target === e.currentTarget) setShowModal(false);
          }}
        >
          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-6 w-full max-w-md max-h-[85vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-bold text-white">记一笔</h3>
              <button
                onClick={() => setShowModal(false)}
                className="text-neutral-400 hover:text-white text-xl leading-none"
              >
                &times;
              </button>
            </div>
            <TransactionForm
              onSuccess={() => {
                fetchTransactions();
                setShowModal(false);
              }}
            />
          </div>
        </div>
      )}

      <div className="flex gap-2">
        {[
          { value: "", label: "全部" },
          { value: "income", label: "收入" },
          { value: "expense", label: "支出" },
          { value: "liability_repayment", label: "还款" },
          { value: "liability_principal_change", label: "借款" },
        ].map((f) => (
          <button
            key={f.value}
            onClick={() => {
              setTypeFilter(f.value);
              setLoading(true);
            }}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
              typeFilter === f.value
                ? "bg-blue-600 text-white"
                : "bg-neutral-800 text-neutral-400 hover:bg-neutral-700"
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      <div className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-neutral-800">
              <th className="text-left text-xs text-neutral-400 px-4 py-3 font-medium">
                日期
              </th>
              <th className="text-left text-xs text-neutral-400 px-4 py-3 font-medium">
                类型
              </th>
              <th className="text-left text-xs text-neutral-400 px-4 py-3 font-medium">
                描述
              </th>
              <th className="text-right text-xs text-neutral-400 px-4 py-3 font-medium">
                金额
              </th>
              <th className="text-right text-xs text-neutral-400 px-4 py-3 font-medium">
                操作
              </th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td
                  colSpan={5}
                  className="text-center text-neutral-500 py-8 text-sm"
                >
                  加载中...
                </td>
              </tr>
            ) : transactions.length === 0 ? (
              <tr>
                <td
                  colSpan={5}
                  className="text-center text-neutral-500 py-8 text-sm"
                >
                  暂无记录，点击上方「记一笔」开始
                </td>
              </tr>
            ) : (
              transactions.map((t) => (
                <tr
                  key={t.id}
                  className="border-b border-neutral-800/50 hover:bg-neutral-800/30"
                >
                  <td className="px-4 py-3 text-sm text-neutral-400">
                    {formatDate(t.transactionDate)}
                    {t.isAutoGenerated && (
                      <span className="ml-2 text-xs bg-neutral-700 text-neutral-300 px-1.5 py-0.5 rounded">
                        自动
                      </span>
                    )}
                  </td>
                  <td className={`px-4 py-3 text-sm ${typeColor(t.type)}`}>
                    {getTransactionTypeLabel(t.type)}
                  </td>
                  <td className="px-4 py-3 text-sm text-white">
                    {t.description}
                    {t.type === "liability_repayment" && t.principalPart > 0 && (
                      <span className="text-xs text-neutral-500 ml-2">
                        本金 {formatMoney(t.principalPart)} + 利息{" "}
                        {formatMoney(t.interestPart)}
                      </span>
                    )}
                  </td>
                  <td className={`px-4 py-3 text-sm text-right font-medium ${typeColor(t.type)}`}>
                    {["income", "asset_income", "liability_principal_change"].includes(t.type)
                      ? "+"
                      : "-"}
                    {formatMoney(Math.abs(t.amount))}
                  </td>
                  <td className="px-4 py-3 text-sm text-right">
                    {!t.isAutoGenerated && (
                      <div className="flex items-center justify-end gap-3">
                        <button
                          onClick={() => startEdit(t)}
                          className="text-blue-400 hover:text-blue-300 text-xs"
                        >
                          编辑
                        </button>
                        <button
                          onClick={() => handleDelete(t.id)}
                          className="text-red-400 hover:text-red-300 text-xs"
                        >
                          删除
                        </button>
                      </div>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Edit modal */}
      {editingTx && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60"
          onClick={(e) => {
            if (e.target === e.currentTarget) setEditingTx(null);
          }}
        >
          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-6 w-full max-w-md">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-bold text-white">编辑记录</h3>
              <button
                onClick={() => setEditingTx(null)}
                className="text-neutral-400 hover:text-white text-xl leading-none"
              >
                &times;
              </button>
            </div>
            <form onSubmit={handleEditSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-neutral-400 mb-1">金额 (元)</label>
                  <input
                    type="number"
                    step="0.01"
                    required
                    value={editForm.amount}
                    onChange={(e) => setEditForm({ ...editForm, amount: e.target.value })}
                    className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm text-neutral-400 mb-1">日期</label>
                  <input
                    type="date"
                    required
                    value={editForm.transactionDate}
                    onChange={(e) => setEditForm({ ...editForm, transactionDate: e.target.value })}
                    className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500 [color-scheme:dark]"
                  />
                </div>
              </div>
              {editingTx.type === "liability_repayment" && (
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm text-neutral-400 mb-1">本金部分 (元)</label>
                    <input
                      type="number"
                      step="0.01"
                      value={editForm.principalPart}
                      onChange={(e) => setEditForm({ ...editForm, principalPart: e.target.value })}
                      className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm text-neutral-400 mb-1">利息部分 (元)</label>
                    <input
                      type="number"
                      step="0.01"
                      value={editForm.interestPart}
                      onChange={(e) => setEditForm({ ...editForm, interestPart: e.target.value })}
                      className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
                    />
                  </div>
                </div>
              )}
              <div>
                <label className="block text-sm text-neutral-400 mb-1">描述</label>
                <input
                  type="text"
                  required
                  value={editForm.description}
                  onChange={(e) => setEditForm({ ...editForm, description: e.target.value })}
                  className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm text-neutral-400 mb-1">备注</label>
                <input
                  type="text"
                  value={editForm.note}
                  onChange={(e) => setEditForm({ ...editForm, note: e.target.value })}
                  className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
                />
              </div>
              <button
                type="submit"
                disabled={editLoading}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2.5 text-sm font-medium transition-colors disabled:opacity-50"
              >
                {editLoading ? "保存中..." : "保存修改"}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
