"use client";

import { useState, useEffect } from "react";
import { TransactionForm } from "@/components/Forms";
import { Modal } from "@/components/Modal";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { TransactionEditModal } from "@/components/TransactionEditModal";
import {
  formatMoney,
  formatDate,
  getTransactionTypeLabel,
} from "@/lib/utils";

interface Transaction {
  id: number;
  type: string;
  amount: number;
  principalPart: number;
  interestPart: number;
  description: string;
  transactionDate: string;
  isAutoGenerated: boolean;
  note: string | null;
  assetName?: string | null;
  liabilityName?: string | null;
}

export default function TransactionsPage() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [showModal, setShowModal] = useState(false);
  const [loading, setLoading] = useState(true);
  const [typeFilter, setTypeFilter] = useState("");
  const [refreshKey, setRefreshKey] = useState(0);
  const [editingTx, setEditingTx] = useState<Transaction | null>(null);
  const [pendingDelete, setPendingDelete] = useState<Transaction | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);
  useEffect(() => {
    let mounted = true;
    const params = new URLSearchParams();
    if (typeFilter) params.set("type", typeFilter);
    fetch(`/api/transactions?${params}`)
      .then((r) => r.json())
      .then((result) => {
        if (mounted) {
          setTransactions(result.data ?? result);
          setLoading(false);
        }
      });
    return () => {
      mounted = false;
    };
  }, [typeFilter, refreshKey]);

  const fetchTransactions = () => setRefreshKey((k) => k + 1);

  const handleDeleteTx = async () => {
    if (!pendingDelete) return;
    setDeleteLoading(true);
    try {
      await fetch(`/api/transactions?id=${pendingDelete.id}`, {
        method: "DELETE",
      });
      setPendingDelete(null);
      fetchTransactions();
    } finally {
      setDeleteLoading(false);
    }
  };

  const typeColor = (type: string) => {
    if (["income", "asset_income"].includes(type)) return "text-green-400";
    if (["expense", "liability_repayment"].includes(type)) return "text-red-400";
    return "text-blue-400";
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-white">记账</h2>
          <p className="text-sm text-neutral-400 mt-1">
            记录收支和资产负债变动
          </p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="bg-green-600 hover:bg-green-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          + 记一笔
        </button>
      </div>

      {/* 记一笔 */}
      <Modal
        open={showModal}
        title="记一笔"
        onClose={() => setShowModal(false)}
      >
        <TransactionForm
          onSuccess={() => {
            fetchTransactions();
            setShowModal(false);
          }}
        />
      </Modal>

      <div className="flex gap-2">
        {[
          { value: "", label: "全部" },
          { value: "income", label: "收入" },
          { value: "expense", label: "支出" },
          { value: "liability_repayment", label: "还款" },
          { value: "liability_principal_change", label: "借款" },
        ].map((f) => (
          <button
            key={f.value}
            onClick={() => {
              setTypeFilter(f.value);
              setLoading(true);
            }}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
              typeFilter === f.value
                ? "bg-blue-600 text-white"
                : "bg-neutral-800 text-neutral-400 hover:bg-neutral-700"
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      <div className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-neutral-800">
              <th className="text-left text-xs text-neutral-400 px-4 py-3 font-medium">
                日期
              </th>
              <th className="text-left text-xs text-neutral-400 px-4 py-3 font-medium">
                类型
              </th>
              <th className="text-left text-xs text-neutral-400 px-4 py-3 font-medium">
                描述
              </th>
              <th className="text-left text-xs text-neutral-400 px-4 py-3 font-medium">
                账户
              </th>
              <th className="text-right text-xs text-neutral-400 px-4 py-3 font-medium">
                金额
              </th>
              <th className="text-right text-xs text-neutral-400 px-4 py-3 font-medium">
                操作
              </th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td
                  colSpan={6}
                  className="text-center text-neutral-500 py-8 text-sm"
                >
                  加载中...
                </td>
              </tr>
            ) : transactions.length === 0 ? (
              <tr>
                <td
                  colSpan={6}
                  className="text-center text-neutral-500 py-8 text-sm"
                >
                  暂无记录，点击上方「记一笔」开始
                </td>
              </tr>
            ) : (
              transactions.map((t) => (
                <tr
                  key={t.id}
                  className="border-b border-neutral-800/50 hover:bg-neutral-800/30"
                >
                  <td className="px-4 py-3 text-sm text-neutral-400">
                    {formatDate(t.transactionDate)}
                    {t.isAutoGenerated && (
                      <span className="ml-2 text-xs bg-neutral-700 text-neutral-300 px-1.5 py-0.5 rounded">
                        自动
                      </span>
                    )}
                  </td>
                  <td className={`px-4 py-3 text-sm ${typeColor(t.type)}`}>
                    {getTransactionTypeLabel(t.type)}
                  </td>
                  <td className="px-4 py-3 text-sm text-white">
                    {t.description}
                    {t.type === "liability_repayment" && t.principalPart > 0 && (
                      <span className="text-xs text-neutral-500 ml-2">
                        本金 {formatMoney(t.principalPart)} + 利息{" "}
                        {formatMoney(t.interestPart)}
                      </span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-sm text-neutral-400">
                    {t.assetName || t.liabilityName || "-"}
                  </td>
                  <td className={`px-4 py-3 text-sm text-right font-medium ${typeColor(t.type)}`}>
                    {["income", "asset_income", "liability_principal_change"].includes(t.type)
                      ? "+"
                      : "-"}
                    {formatMoney(Math.abs(t.amount))}
                  </td>
                  <td className="px-4 py-3 text-sm text-right">
                    {!t.isAutoGenerated && (
                      <div className="flex items-center justify-end gap-3">
                        <button
                          onClick={() => setEditingTx(t)}
                          className="text-blue-400 hover:text-blue-300 text-xs"
                        >
                          编辑
                        </button>
                        <button
                          onClick={() => setPendingDelete(t)}
                          className="text-red-400 hover:text-red-300 text-xs"
                        >
                          删除
                        </button>
                      </div>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* 编辑明细 */}
      <TransactionEditModal
        transaction={editingTx}
        onClose={() => setEditingTx(null)}
        onSaved={fetchTransactions}
      />

      {/* 删除明细确认 */}
      <ConfirmDialog
        open={!!pendingDelete}
        title="删除明细"
        message="确定删除这条记录吗？删除后相关账户余额会按剩余流水同步调整。"
        loading={deleteLoading}
        onCancel={() => setPendingDelete(null)}
        onConfirm={handleDeleteTx}
      />
    </div>
  );
}
